// frontend-solid/src/components/admin/AdminPage.tsx
import { Component, Show, Suspense, lazy } from 'solid-js'; // Added lazy, Suspense
import { useAuth } from '@/context/AuthContext';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/Tabs'; // Import Tabs components
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card'; // Use Card, added Desc
import LoadingSpinner from '@/components/shared/LoadingSpinner'; // Import LoadingSpinner

// Lazy load tab contents for better initial performance
const UserManagement = lazy(() => import('./UserManagement'));
const SettingsForm = lazy(() => import('./SettingsForm'));
const SslConfig = lazy(() => import('./SslConfig'));
const LogViewer = lazy(() => import('./LogViewer'));

import styles from './AdminPage.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils'; // Import cn if needed

const AdminPage: Component = () => {
    const [authState] = useAuth();
    const user = () => authState.user; // Reactive accessor for user

    return (
        <div class={styles.adminPageContainer}>
            <Show when={user()?.role === 'admin'}
                fallback={
                    // Access Denied Message
                    <Card class={styles.accessDeniedCard}>
                        <CardHeader>
                            <CardTitle class={styles.accessDeniedTitle}>Access Denied</CardTitle>
                            <CardDescription>Administrator privileges are required to view this page.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <p>You do not have the necessary permissions.</p>
                        </CardContent>
                    </Card>
                }
            >
                {/* Admin Content */}
                <div class={styles.pageHeaderContainer}>
                     <div class={styles.pageHeaderText}>
                        <h1 class={styles.pageTitle}>Admin Panel</h1>
                        <p class={styles.pageDescription}>Manage application users, settings, and logs.</p>
                     </div>
                     {/* Optional global admin actions button */}
                </div>

                <Tabs defaultValue="users" class={styles.tabsWrapper}>
                    <TabsList>
                        <TabsTrigger value="users">User Management</TabsTrigger>
                        <TabsTrigger value="settings">App Settings</TabsTrigger>
                        <TabsTrigger value="ssl">SSL Config</TabsTrigger>
                        <TabsTrigger value="logs">System Logs</TabsTrigger>
                    </TabsList>

                    {/* Wrap each content in Suspense for lazy loading */}
                    <TabsContent value="users">
                        <Suspense fallback={<div class="p-10 flex justify-center"><LoadingSpinner size="lg"/></div>}>
                           <UserManagement />
                        </Suspense>
                    </TabsContent>
                    <TabsContent value="settings">
                         <Suspense fallback={<div class="p-10 flex justify-center"><LoadingSpinner size="lg"/></div>}>
                             <SettingsForm />
                         </Suspense>
                    </TabsContent>
                    <TabsContent value="ssl">
                         <Suspense fallback={<div class="p-10 flex justify-center"><LoadingSpinner size="lg"/></div>}>
                             <SslConfig />
                         </Suspense>
                    </TabsContent>
                    <TabsContent value="logs">
                         <Suspense fallback={<div class="p-10 flex justify-center"><LoadingSpinner size="lg"/></div>}>
                             <LogViewer />
                         </Suspense>
                    </TabsContent>
                </Tabs>
            </Show>
        </div>
    );
};

export default AdminPage;

// frontend-react/src/components/admin/AdminPage.tsx
import React from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import UserManagement from './UserManagement';
import SettingsForm from './SettingsForm';
// Removed SslConfig import
import LogViewer from './LogViewer';
import DatabaseManagement from './DatabaseManagement';
import { useAuth } from '@/hooks/useAuth';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

const AdminPage: React.FC = () => {
  const { user } = useAuth();

  if (user?.role !== 'admin') {
      return (
          <div className='p-4 md:p-6'>
              <Card className='border-destructive'>
                  <CardHeader>
                      <CardTitle className='text-destructive'>Access Denied</CardTitle>
                  </CardHeader>
                  <CardContent>
                      <p>You do not have the necessary permissions to view this page. Administrator privileges are required.</p>
                  </CardContent>
              </Card>
          </div>
      );
  }

  return (
    <div className="space-y-6">
      <div className='flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4'>
        <div>
           <h1 className="text-2xl font-bold">Admin Panel</h1>
           {/* Updated description */}
           <p className='text-muted-foreground'>Manage application users, settings, database, and logs.</p>
        </div>
      </div>

      <Tabs defaultValue="users" className="w-full">
        <div className="overflow-x-auto pb-1 border-b">
            {/* Removed SSL Tab */}
            <TabsList className='inline-flex w-auto min-w-full'>
                <TabsTrigger value="users">User Management</TabsTrigger>
                <TabsTrigger value="settings">App Settings</TabsTrigger>
                <TabsTrigger value="database">Database</TabsTrigger>
                <TabsTrigger value="logs">System Logs</TabsTrigger>
            </TabsList>
        </div>
        <TabsContent value="users" className='mt-6'>
           <UserManagement />
        </TabsContent>
        <TabsContent value="settings" className='mt-6'>
            <SettingsForm />
        </TabsContent>
        {/* Removed SSL Tab Content */}
        <TabsContent value="database" className='mt-6'>
             <DatabaseManagement />
         </TabsContent>
        <TabsContent value="logs" className='mt-6'>
            <LogViewer />
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default AdminPage;
