// frontend-solid/src/components/admin/SslConfig.tsx
import { Component, createSignal, Show, onCleanup } from 'solid-js';
// Removed @modular-forms/solid imports
import { z, ZodIssue } from 'zod';
import { sslSchema, SslFormData } from '@/lib/zodSchemas';
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';

import { Button } from '@/components/ui/Button';
import { Textarea, type TextareaProps } from '@/components/ui/Textarea';
import { FormLabel } from '@/components/ui/FormLabel';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/Alert';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import { Icon } from '@/components/shared/Icon';
// import { useNotifications } from '@/context/NotificationContext'; // TODO: Use notifications
import { cn } from '@/lib/utils';
import styles from './SslConfig.module.css'; // Import CSS Module (Typed)
import type { JSX } from 'solid-js';


const SslConfig: Component = () => {
    const [authState] = useAuth();
    const [uploadStatus, setUploadStatus] = createSignal<'idle' | 'saving' | 'success' | 'error'>('idle');
    const [generateStatus, setGenerateStatus] = createSignal<'idle' | 'generating' | 'success' | 'error'>('idle');
    const [uploadError, setUploadError] = createSignal<string | null>(null);
    const [generateError, setGenerateError] = createSignal<string | null>(null);
    // const { addNotification } = useNotifications(); // TODO: Inject notification hook

    let uploadSuccessTimeout: ReturnType<typeof setTimeout> | undefined;
    let generateSuccessTimeout: ReturnType<typeof setTimeout> | undefined;

    // State for upload form
    const [sslKey, setSslKey] = createSignal('');
    const [sslCert, setSslCert] = createSignal('');
    const [formErrors, setFormErrors] = createSignal<Partial<Record<keyof SslFormData, string>>>({});

    const isFormDirty = () => sslKey() !== '' || sslCert() !== '';
    // REMOVED hasFormErrors check

    onCleanup(() => {
        if (uploadSuccessTimeout) clearTimeout(uploadSuccessTimeout);
        if (generateSuccessTimeout) clearTimeout(generateSuccessTimeout);
    });

    // Validation function
    const validateUploadForm = (): boolean => {
        setFormErrors({}); // Clear previous errors
        const formData = { key: sslKey(), cert: sslCert() };
        const result = sslSchema.safeParse(formData);
        if (!result.success) {
            const errors: Partial<Record<keyof SslFormData, string>> = {};
            result.error.errors.forEach((err: ZodIssue) => {
                if (err.path.length > 0) {
                    errors[err.path[0] as keyof SslFormData] = err.message;
                }
            });
            setFormErrors(errors);
            return false;
        }
        return true;
    };

    const handleUpload = async (event: Event) => {
        event.preventDefault();
        const token = authState.token;
        if (!token || !validateUploadForm()) return; // Validate before submit

        setUploadStatus('saving'); setUploadError(null);
        if (uploadSuccessTimeout) clearTimeout(uploadSuccessTimeout);

        try {
            // Values from signals
            await api.uploadSsl({ key: sslKey(), cert: sslCert() }, token);
            setUploadStatus('success');
            // Clear form on success
            setSslKey('');
            setSslCert('');
            setFormErrors({});
            uploadSuccessTimeout = setTimeout(() => setUploadStatus('idle'), 3000);
            // TODO: addNotification({ type: 'success', message: 'SSL config uploaded. Restart server to apply.' });
        } catch (err: any) {
            const msg = err.message || "Failed to upload SSL config.";
            setUploadError(msg);
            setUploadStatus('error');
            // TODO: addNotification({ type: 'error', message: `Upload failed: ${msg}` });
        }
    };

    // --- Generate Action ---
    const handleGenerate = async () => {
        const token = authState.token;
        if (!token) return;
        if (!window.confirm("Generate new self-signed certificate? This overwrites existing config and requires server restart. (For testing only)")) return;

        setGenerateStatus('generating'); setGenerateError(null);
        if (generateSuccessTimeout) clearTimeout(generateSuccessTimeout);

        try {
            await api.generateSsl(token);
            setGenerateStatus('success');
            generateSuccessTimeout = setTimeout(() => setGenerateStatus('idle'), 3000);
            // TODO: addNotification({ type: 'success', message: 'Self-signed certificate generated. Restart server to apply.' });
        } catch (err: any) {
             const msg = err.message || "Failed to generate SSL certificate.";
             setGenerateError(msg);
             setGenerateStatus('error');
             // TODO: addNotification({ type: 'error', message: `Generation failed: ${msg}` });
        }
    };

    return (
        <div class={styles.sslConfigContainer}>
            {/* Upload Card */}
            <Card class={styles.sslCard}>
                <CardHeader>
                    <CardTitle>Upload Existing SSL</CardTitle>
                    <CardDescription>Paste private key and certificate (PEM). Requires restart.</CardDescription>
                </CardHeader>
                <CardContent>
                    <form onSubmit={handleUpload} class={styles.sslForm}>
                        {/* Status Messages */}
                        <Show when={uploadStatus() === 'error' && uploadError()}>
                           {(err) => <Alert variant="destructive"><AlertTitle>Error</AlertTitle><AlertDescription>{err()}</AlertDescription></Alert>}
                        </Show>
                         <Show when={uploadStatus() === 'success'}>
                            <Alert variant="success"><AlertTitle>Upload Successful</AlertTitle><AlertDescription>SSL config uploaded. Restart needed.</AlertDescription></Alert>
                         </Show>

                         {/* Key Input */}
                        <div class={styles.formGroup}>
                            <FormLabel for="ssl-key-input" required invalid={!!formErrors().key}>Private Key (.key)</FormLabel>
                            <Textarea
                                id="ssl-key-input"
                                name="key"
                                value={sslKey()}
                                // --- FIX: Removed validateForm() call ---
                                onInput={(e) => { setSslKey(e.currentTarget.value); }}
                                required
                                placeholder="-----BEGIN PRIVATE KEY-----\n..."
                                aria-invalid={!!formErrors().key}
                                aria-errormessage="ssl-key-error"
                                class={styles.sslTextarea}
                                rows={8}
                            />
                             <Show when={formErrors().key}><p id="ssl-key-error" class={styles.errorMessage}>{formErrors().key}</p></Show>
                        </div>

                        {/* Cert Input */}
                        <div class={styles.formGroup}>
                             <FormLabel for="ssl-cert-input" required invalid={!!formErrors().cert}>Certificate (.crt/.pem)</FormLabel>
                             <Textarea
                                 id="ssl-cert-input"
                                 name="cert"
                                 value={sslCert()}
                                 // --- FIX: Removed validateForm() call ---
                                 onInput={(e) => { setSslCert(e.currentTarget.value); }}
                                 required
                                 placeholder="-----BEGIN CERTIFICATE-----\n..."
                                 aria-invalid={!!formErrors().cert}
                                 aria-errormessage="ssl-cert-error"
                                 class={styles.sslTextarea}
                                 rows={8}
                             />
                              <Show when={formErrors().cert}><p id="ssl-cert-error" class={styles.errorMessage}>{formErrors().cert}</p></Show>
                         </div>

                         {/* --- FIX: Simplified disabled check --- */}
                        <Button type="submit" disabled={uploadStatus() === 'saving' || !isFormDirty()} class={styles.actionButton}>
                            <Show when={uploadStatus() === 'saving'} fallback={<><Icon name="UploadCloud" size="1em" class={styles.actionButtonIcon}/> Upload SSL Files</>}>
                                <LoadingSpinner size="sm" class={styles.actionButtonIcon} /> Saving...
                            </Show>
                        </Button>
                    </form>
                </CardContent>
            </Card>

            {/* Generate Card */}
             <Card class={styles.sslCard}>
                <CardHeader>
                    <CardTitle>Generate Self-Signed SSL</CardTitle>
                    <CardDescription>Generate certificate for testing/dev (not production). Requires restart.</CardDescription>
                </CardHeader>
                <CardContent class="space-y-4">
                     {/* Status Messages */}
                    <Show when={generateStatus() === 'error' && generateError()}>
                        {(err) => <Alert variant="destructive"><AlertTitle>Error</AlertTitle><AlertDescription>{err()}</AlertDescription></Alert>}
                    </Show>
                    <Show when={generateStatus() === 'success'}>
                         <Alert variant="success"><AlertTitle>Generation Successful</AlertTitle><AlertDescription>Self-signed cert generated. Restart needed.</AlertDescription></Alert>
                    </Show>

                    <Button onClick={handleGenerate} disabled={generateStatus() === 'generating'} variant="outline" class={styles.actionButton}>
                        <Show when={generateStatus() === 'generating'} fallback={<><Icon name="RefreshCcw" size="1em" class={styles.actionButtonIcon}/> Generate New Certificate</>}>
                             <LoadingSpinner size="sm" class={styles.actionButtonIcon} /> Generating...
                         </Show>
                    </Button>
                </CardContent>
             </Card>
        </div>
    );
};

export default SslConfig;

// frontend-react/src/components/admin/SslConfig.tsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"; // Import Card components
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
import { sslSchema, SslFormData } from '@/lib/zodSchemas'; // Import schema and type
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"; // Import Alert for status messages
import { CheckCircle, UploadCloud, RefreshCcw } from 'lucide-react'; // Import icons
import { cn } from '@/lib/utils'; // Import cn for conditional classes

const SslConfig: React.FC = () => {
    const { token } = useAuth();
    // Separate state for upload and generate operations
    const [uploadStatus, setUploadStatus] = useState<'idle' | 'saving' | 'success' | 'error'>('idle');
    const [generateStatus, setGenerateStatus] = useState<'idle' | 'generating' | 'success' | 'error'>('idle');
    const [uploadError, setUploadError] = useState<string | null>(null);
    const [generateError, setGenerateError] = useState<string | null>(null);

    const { register, handleSubmit, reset, formState: { errors, isDirty: isUploadFormDirty } } = useForm<SslFormData>({
        resolver: zodResolver(sslSchema),
        defaultValues: { key: '', cert: '' }, // Start with empty fields
    });

    // Handle uploading provided key/cert
    const handleUpload = async (data: SslFormData) => {
        if (!token) return;
        setUploadStatus('saving');
        setUploadError(null);
        try {
            // Ensure data structure matches SslConfig interface { key: string; cert: string }
            await api.uploadSsl({ key: data.key, cert: data.cert }, token);
            setUploadStatus('success');
            reset({ key: '', cert: '' }); // Clear form on success
            setTimeout(() => setUploadStatus('idle'), 3000); // Reset status after delay
        } catch (err: any) {
            setUploadError(err.message || "Failed to upload SSL configuration.");
            setUploadStatus('error');
        }
    };

    // Handle generating a self-signed certificate
    const handleGenerate = async () => {
        if (!token) return;
        // Confirmation dialog
        if (!window.confirm("This will generate a new self-signed certificate and overwrite any existing configuration. This is only recommended for testing/development. Continue?")) return;

        setGenerateStatus('generating');
        setGenerateError(null);
        try {
            await api.generateSsl(token);
            setGenerateStatus('success');
            setTimeout(() => setGenerateStatus('idle'), 3000); // Reset status after delay
            // Optionally fetch and display the new cert/key? Or just show success.
            // alert("Self-signed certificate generated successfully. Server might need a restart.");
        } catch (err: any) {
             setGenerateError(err.message || "Failed to generate SSL certificate.");
             setGenerateStatus('error');
        }
    };

    // Use a grid layout to place cards side-by-side on larger screens
    return (
        <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
             {/* Upload Card - forced white background */}
             <Card className="bg-white dark:bg-white text-neutral-900 dark:text-neutral-900">
                 <CardHeader>
                     <CardTitle>Upload Existing SSL</CardTitle>
                     <CardDescription>Paste your private key and certificate (PEM format). Requires server restart.</CardDescription>
                 </CardHeader>
                <CardContent>
                    <form onSubmit={handleSubmit(handleUpload)} className="space-y-4">
                         {/* Display upload status/error messages */}
                         {uploadStatus === 'error' && uploadError && <ErrorDisplay message={uploadError} />}
                         {uploadStatus === 'success' && (
                            <Alert variant="default" className="border-green-600 bg-green-50 dark:bg-green-50 text-green-700 dark:text-green-700">
                                <CheckCircle className="h-5 w-5 text-green-600" />
                                <AlertTitle>Upload Successful</AlertTitle>
                                <AlertDescription>SSL configuration uploaded. Server restart needed.</AlertDescription>
                            </Alert>
                         )}

                         {/* Private Key Input */}
                         <div className="grid gap-1.5">
                             <Label htmlFor="ssl-key">Private Key (.key)</Label>
                             <Textarea
                                id="ssl-key"
                                {...register('key')}
                                rows={8}
                                placeholder="-----BEGIN PRIVATE KEY-----\n..."
                                // Use mono font for keys/certs, apply error style
                                className={cn('font-mono text-xs', errors.key && "border-destructive")}
                                aria-invalid={!!errors.key}
                             />
                             {errors.key && <p className="text-xs text-destructive">{errors.key.message}</p>}
                         </div>

                         {/* Certificate Input */}
                         <div className="grid gap-1.5">
                             <Label htmlFor="ssl-cert">Certificate (.crt/.pem)</Label>
                             <Textarea
                                id="ssl-cert"
                                {...register('cert')}
                                rows={8}
                                placeholder="-----BEGIN CERTIFICATE-----\n..."
                                // Use mono font, apply error style
                                className={cn('font-mono text-xs', errors.cert && "border-destructive")}
                                aria-invalid={!!errors.cert}
                             />
                             {errors.cert && <p className="text-xs text-destructive">{errors.cert.message}</p>}
                         </div>

                         {/* Upload Button */}
                         <Button type="submit" disabled={uploadStatus === 'saving' || !isUploadFormDirty}>
                             {uploadStatus === 'saving' && <LoadingSpinner size="sm" className="mr-2" />}
                             <UploadCloud className="mr-2 h-4 w-4" /> Upload SSL Files
                         </Button>
                    </form>
                </CardContent>
             </Card>

            {/* Generate Card - forced white background */}
            <Card className="bg-white dark:bg-white text-neutral-900 dark:text-neutral-900">
                <CardHeader>
                     <CardTitle>Generate Self-Signed SSL</CardTitle>
                     <CardDescription>Generate a new certificate for testing/development (not for production). Requires server restart.</CardDescription>
                </CardHeader>
                <CardContent className='space-y-4'>
                    {/* Display generate status/error messages */}
                    {generateStatus === 'error' && generateError && <ErrorDisplay message={generateError} />}
                    {generateStatus === 'success' && (
                       <Alert variant="default" className="border-green-600 bg-green-50 dark:bg-green-50 text-green-700 dark:text-green-700">
                           <CheckCircle className="h-5 w-5 text-green-600" />
                           <AlertTitle>Generation Successful</AlertTitle>
                           <AlertDescription>Self-signed certificate generated. Server restart may be required.</AlertDescription>
                       </Alert>
                    )}

                    {/* Generate Button */}
                    <Button
                        onClick={handleGenerate}
                        disabled={generateStatus === 'generating'}
                        variant="outline" // Use outline style for less emphasis than upload
                    >
                         {generateStatus === 'generating' && <LoadingSpinner size="sm" className="mr-2" />}
                        <RefreshCcw className="mr-2 h-4 w-4" /> Generate New Certificate
                    </Button>
                     {/* Optional: Add info about where certs are stored */}
                     {/* <p className='text-xs text-muted-foreground pt-2'>Certificates will be stored in the configured path on the server.</p> */}
                </CardContent>
            </Card>
        </div>
    );
};

export default SslConfig;
