// frontend-react/src/components/layout/Sidebar.tsx
import React from 'react';
import { NavLink, useNavigate } from 'react-router-dom'; // Use NavLink for active styling
import { Button } from '@/components/ui/button';
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from '@/lib/utils';
import { useAuth } from '@/hooks/useAuth';
// Use specific icons for clarity
import {
  LayoutDashboard, StickyNote, Tag, PenTool, Archive, ShieldAlert, LogOut, FileSearch // Added FileSearch
} from 'lucide-react';
import { toast } from "sonner"; // Import toast for logout feedback

interface SidebarProps {
  className?: string;
}

const Sidebar: React.FC<SidebarProps> = ({ className }) => {
  const { logout, user } = useAuth();
  const navigate = useNavigate();
  const isAdmin = user?.role === 'admin';
  // Added check for employee role
  const isEmployee = user?.role === 'employee';
  const isUserRole = user?.role === 'user'; // Check for 'user' role

  const handleLogout = async () => {
      try {
          await logout();
      } catch (error: any) {
          toast.error(`Logout failed: ${error.message}`);
      }
  }

  // Define navigation items based on roles
  const navItems = [
    { path: '/', label: 'Dashboard', icon: LayoutDashboard, exact: true, roles: ['admin', 'employee', 'user'] }, // All roles see dashboard
    { path: '/archive', label: 'Archive', icon: isUserRole ? FileSearch : Archive, roles: ['admin', 'employee', 'user'] }, // All roles can access Archive (permissions handled inside)
    { path: '/signatures', label: 'Signatures', icon: PenTool, roles: ['admin', 'employee'] }, // Only admin/employee manage signatures
    { path: '/tags', label: 'Tags', icon: Tag, roles: ['admin', 'employee'] }, // Only admin/employee manage tags
    { path: '/notes', label: 'Notes', icon: StickyNote, roles: ['admin', 'employee'] }, // Only admin/employee access notes
    { path: '/admin', label: 'Admin', icon: ShieldAlert, roles: ['admin'] }, // Only admin sees Admin section
  ].filter(item => item.roles.includes(user?.role || '')); // Filter items based on current user's role


  return (
    <aside className={cn(
      "w-64 bg-sidebar text-sidebar-foreground border-r border-sidebar-border flex flex-col",
      className
    )}>
       <div className="p-4 border-b border-sidebar-border">
         <h2 className="text-lg font-semibold">JezArch FE</h2>
         {user && <span className="text-sm text-muted-foreground block truncate">Logged in as: {user.login} ({user.role})</span>}
       </div>

      <ScrollArea className="flex-1 px-4 py-2">
        <nav className="flex flex-col space-y-1">
          {navItems.map((item) => (
            <NavLink
              key={item.path}
              to={item.path}
              end={item.exact}
              className={({ isActive }) =>
                cn(
                  "inline-flex items-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
                  "justify-start px-3 py-2",
                  (isActive || location.pathname.startsWith(item.path + '/'))
                    ? "bg-sidebar-accent text-sidebar-accent-foreground font-semibold"
                    : "hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
                )
              }
            >
               <item.icon className="mr-2 h-4 w-4" />
               {item.label}
            </NavLink>
          ))}
        </nav>
      </ScrollArea>

       <div className="p-4 mt-auto border-t border-sidebar-border">
         <Button variant="outline" className="w-full justify-start" onClick={handleLogout}>
           <LogOut className="mr-2 h-4 w-4" />
           Logout
         </Button>
       </div>
    </aside>
  );
};

export default Sidebar;

// frontend-solid/src/components/layout/Sidebar.tsx
import { Component, For, Show } from 'solid-js'; // Added Show
// Replaced NavLink with A and added useMatch for active state logic
import { A, useNavigate, useLocation, useMatch } from '@solidjs/router';
import { useAuth } from '@/context/AuthContext';
import { Icon, IconName } from '@/components/shared/Icon';
import { Button } from '@/components/ui/Button';
import styles from './Sidebar.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils'; // Import cn

interface NavItem {
    path: string;
    label: string;
    icon: IconName;
    exact?: boolean;
    adminOnly?: boolean;
}

const Sidebar: Component = () => {
    const [authState, { logout }] = useAuth();
    const navigate = useNavigate(); // Keep useNavigate
    const location = useLocation();

    const isAdmin = () => authState.user?.role === 'admin';

    const handleLogout = async () => {
        await logout();
        // Redirect handled by App/ProtectedRoute
    };

    const navItems: NavItem[] = [
        { path: '/', label: 'Dashboard', icon: 'LayoutDashboard', exact: true },
        { path: '/archive', label: 'Archive', icon: 'Archive' },
        { path: '/signatures', label: 'Signatures', icon: 'PenTool' },
        { path: '/tags', label: 'Tags', icon: 'Tag' },
        { path: '/notes', label: 'Notes', icon: 'StickyNote' },
        { path: '/admin', label: 'Admin', icon: 'ShieldAlert', adminOnly: true },
    ];

    const filteredNavItems = () => navItems.filter(item => !item.adminOnly || isAdmin());

    // Function to determine if a NavLink should be active using useMatch
    const isLinkActive = (path: string, exact?: boolean) => {
        const match = useMatch(() => path); // Use match function
        // For exact match, check if match exists and path is exactly the same (ignoring trailing slash perhaps)
        if (exact) {
            // Normalize paths to remove trailing slashes before comparison
            const currentPathname = location.pathname.replace(/\/$/, "");
            const itemPath = path.replace(/\/$/, "");
            return !!match() && currentPathname === itemPath;
        }
        // For non-exact match, just check if match exists (covers parent paths)
        return !!match();
    };

    return (
        <aside class={styles.sidebarContainer}>
            <div class={styles.sidebarHeader}>
                <h2 class={styles.sidebarTitle}>JezArch Solid</h2>
                <Show when={authState.user}>
                    {(user) => ( // user() is the accessor for the user object
                         <span class={styles.sidebarUserInfo} title={`Logged in as: ${user().login} (${user().role})`}>
                            {user().login} ({user().role})
                        </span>
                    )}
                </Show>
            </div>

            {/* Use basic div for scroll area with CSS module styles */}
            <div class={styles.scrollArea}>
                <nav class={styles.navList}>
                    <For each={filteredNavItems()}>
                        {(item) => (
                            <A
                                href={item.path}
                                // Use cn to apply classes conditionally based on active state
                                class={cn(
                                    styles.navLinkBase,
                                    isLinkActive(item.path, item.exact) ? styles.navLinkActive : styles.navLinkInactive
                                )}
                                // 'end' prop is not used with <A>, manual active check needed
                            >
                                <Icon name={item.icon} class={styles.navLinkIcon} />
                                {item.label}
                            </A>
                        )}
                    </For>
                </nav>
            </div>

            <div class={styles.sidebarFooter}>
                <Button
                    variant="outline"
                    class={styles.logoutButton} // Apply specific class
                    onClick={handleLogout}
                >
                    <Icon name="LogOut" class={styles.navLinkIcon} />
                    Logout
                </Button>
            </div>
        </aside>
    );
};

export default Sidebar;
