// frontend-solid/src/components/archive/ArchivePage.tsx
import { Component, createSignal, createResource, Show, createMemo, Suspense, onMount } from 'solid-js';
import { useSearchParams, useNavigate, A } from '@solidjs/router';
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';
import type { Tag } from '../../../../backend/src/functionalities/tag/models';
import type { ArchiveDocument, ArchiveDocumentSearchResult, ArchiveDocumentType } from '../../../../backend/src/functionalities/archive/document/models';
import type { SearchRequest, SearchQueryElement } from '../../../../backend/src/utils/search';

import { Button } from '@/components/ui/Button';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogBody } from '@/components/ui/Dialog'; // Added DialogBody
import DocumentList from './DocumentList';
import DocumentForm from './DocumentForm';
import DocumentPreviewDialog from './DocumentPreviewDialog';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import SearchBar, { type SearchFieldOption } from '@/components/shared/SearchBar'; // Import SearchBar
import { Pagination } from '@/components/shared/Pagination'; // Import Pagination
import { Icon } from '@/components/shared/Icon';
import { Card, CardContent, CardHeader } from '@/components/ui/Card';
import styles from './ArchivePage.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils'; // Import cn if needed

const ARCHIVE_PAGE_SIZE = 10;

const ArchivePage: Component = () => {
    const [authState] = useAuth();
    const navigate = useNavigate();
    const [searchParams] = useSearchParams();

    // Reactive signals for state
    const [editingDoc, setEditingDoc] = createSignal<ArchiveDocument | null>(null);
    const [previewingDoc, setPreviewingDoc] = createSignal<ArchiveDocumentSearchResult | null>(null);
    const [isFormOpen, setIsFormOpen] = createSignal(false);
    const [isPreviewOpen, setIsPreviewOpen] = createSignal(false);

    // Form specific state signals (passed to DocumentForm)
    const [formInitialType, setFormInitialType] = createSignal<ArchiveDocumentType | undefined>(undefined);
    const [formInitialParentId, setFormInitialParentId] = createSignal<number | undefined>(undefined);
    const [formInitialParentTitle, setFormInitialParentTitle] = createSignal<string | undefined>(undefined);
    const [formDialogTitle, setFormDialogTitle] = createSignal("Create Item");

    // Search & Pagination state signals
    const [searchQuery, setSearchQuery] = createSignal<SearchRequest['query']>([]);
    const [currentPage, setCurrentPage] = createSignal(1);

    // Derived signal for parentUnitId from searchParams
    const parentUnitId = createMemo(() => {
        const id = searchParams.unitId;
        return id ? parseInt(id, 10) : null;
    });

    // --- Resource for Parent Unit Details ---
    const [parentUnitResource] = createResource(
        () => ({ token: authState.token, id: parentUnitId() }), // Depends on token and reactive parentUnitId
        async ({ token, id }) => {
            if (!token || id === null || isNaN(id)) return null; // No fetch if no valid ID/token
            console.log(`Fetching parent unit: ${id}`);
            try {
                const unit = await api.getArchiveDocumentById(id, token);
                if (unit.type !== 'unit') throw new Error(`Item ID ${id} is not a Unit.`);
                return unit;
            } catch (err: any) {
                console.error("Fetch Parent Unit Error:", err);
                // TODO: Toast error
                throw err; // Let resource handle error state
            }
        }
    );

    // --- Resource for Available Tags (for SearchBar) ---
    const [availableTags] = createResource(
        () => authState.token,
        async (token) => {
            if (!token) return [];
            try { return (await api.getAllTags(token)).sort((a, b) => a.name.localeCompare(b.name)); }
            catch { console.error("Failed to load tags for search"); return []; }
        }, { initialValue: [] }
    );

    // --- Resource for Archive Documents ---
    const [documentsData, { refetch: refetchDocuments }] = createResource(
        // Dependencies: token, parent ID readiness, current page, search query
        () => ({
            token: authState.token,
            parentId: parentUnitId(), // Reactive parent ID
            page: currentPage(),
            query: searchQuery(),
            // Only fetch if parent is resolved (or not needed), and user is authenticated
            isReady: authState.token && (parentUnitId() === null || !parentUnitResource.loading)
        }),
        async ({ token, parentId, page, query, isReady }) => {
            if (!isReady) return { data: [], totalSize: 0, totalPages: 1, page: 1 }; // Don't fetch if not ready

            // Check if parent fetch resulted in error
             if (parentId !== null && parentUnitResource.error) {
                  console.warn("Skipping document fetch due to parent unit error.");
                  return { data: [], totalSize: 0, totalPages: 1, page: 1 };
             }

            console.log(`Fetching archive docs - Parent: ${parentId}, Page: ${page}, Query:`, query);
            let finalQuery: SearchQueryElement[] = [...query];

            // Apply parent filter
            if (parentId !== null && !isNaN(parentId)) {
                 finalQuery = finalQuery.filter(q => q.field !== 'parentUnitArchiveDocumentId'); // Remove existing parent filter if any
                 finalQuery.push({ field: 'parentUnitArchiveDocumentId', condition: 'EQ', value: parentId, not: false });
            } else {
                 // Root level filtering (only non-admin see active/owned by default)
                 const user = authState.user;
                 if (user?.role !== 'admin') {
                     // Apply active filter unless already present
                     if (!finalQuery.some(q => q.field === 'active')) {
                          finalQuery.push({ field: 'active', condition: 'EQ', value: true, not: false });
                     } else { // Ensure non-admins cannot override active=true
                          finalQuery = finalQuery.map(q => q.field === 'active' ? { ...q, value: true } : q) as SearchQueryElement[];
                     }
                     // Apply owner filter unless already present
                     if (!finalQuery.some(q => q.field === 'ownerUserId') && user?.userId) {
                          finalQuery.push({ field: 'ownerUserId', condition: 'EQ', value: user.userId, not: false });
                     }
                 }
            }

            const searchRequest: SearchRequest = { query: finalQuery, page, pageSize: ARCHIVE_PAGE_SIZE };
            try {
                // Ensure token is not null before passing
                if (!token) throw new Error("Authentication token missing.");
                return await api.searchArchiveDocuments(searchRequest, token);
            } catch (error) {
                console.error("Fetch Archive Docs Error:", error);
                // TODO: Toast error
                throw error;
            }
        },
        { initialValue: { data: [], totalSize: 0, totalPages: 1, page: 1 } }
    );

    // --- Event Handlers ---
    const handleEdit = (doc: ArchiveDocument) => {
        const user = authState.user;
        if (!user || (user.role !== 'admin' && user.userId !== doc.ownerUserId)) {
            // TODO: Toast error
            console.error("Permission denied to edit item."); return;
        }
        setEditingDoc(doc);
        setFormInitialType(undefined); // Reset form specific state
        setFormInitialParentId(undefined);
        setFormInitialParentTitle(undefined);
        setFormDialogTitle(`Edit ${doc.type === 'unit' ? 'Unit' : 'Document'}`);
        setIsFormOpen(true);
    };

    const handleCreateNew = () => {
         const parent = parentUnitResource(); // Get current parent data
         if (parentUnitId() !== null && !parent) {
             // TODO: Toast warning - Parent still loading or failed to load
             console.warn("Cannot create item: Parent unit data not available."); return;
         }

        setEditingDoc(null);
        if (parentUnitId() !== null && parent) { // Creating inside a specific unit
            setFormInitialType('document'); // Can only create documents inside units? (Assumption)
            setFormInitialParentId(parentUnitId()!);
            setFormInitialParentTitle(parent.title);
            setFormDialogTitle(`Create Document in Unit "${parent.title}"`);
        } else { // Creating at root level
            setFormInitialType(undefined); // Allow choosing type
            setFormInitialParentId(undefined);
            setFormInitialParentTitle(undefined);
            setFormDialogTitle("Create New Item");
        }
        setIsFormOpen(true);
    };

    const handleDisable = async (docId: number) => {
        const token = authState.token;
        const user = authState.user;
        const docToDisable = documentsData()?.data.find(d => d.archiveDocumentId === docId) ?? editingDoc() ?? previewingDoc(); // Find doc from list/editing/previewing state

        if (!token || !docId || !user || !docToDisable) { /* TODO: Toast error */ return; }
        if (user.role !== 'admin' && user.userId !== docToDisable.ownerUserId) { /* TODO: Toast error */ return; }
        if (!window.confirm(`Disable this ${docToDisable.type}? It can be recovered by an admin.`)) return;

        try {
            await api.disableArchiveDocument(docId, token);
            // TODO: Toast success
            // Adjust page and refetch if needed
            const currentTotal = documentsData()?.totalSize ?? 0;
            const newTotal = currentTotal - 1;
            const newTotalPages = Math.max(1, Math.ceil(newTotal / ARCHIVE_PAGE_SIZE));
            if (currentPage() > newTotalPages && newTotalPages > 0) { // Ensure newTotalPages is positive
                setCurrentPage(newTotalPages); // Triggers refetch
            } else {
                refetchDocuments();
            }
            // Close preview if the disabled item was being previewed
            if (previewingDoc()?.archiveDocumentId === docId) setIsPreviewOpen(false);
        } catch (err: any) {
            console.error("Disable Error:", err);
             // TODO: Toast error
        }
    };

    const handleSaveSuccess = () => {
        setIsFormOpen(false); // Close dialog
        refetchDocuments(); // Refresh the list
        // TODO: Toast success
    };

    const handlePreview = async (doc: ArchiveDocumentSearchResult) => {
        const token = authState.token;
        if (!token) return;
        // Preview might need full details, fetch if necessary, or use search result directly
        setPreviewingDoc(doc); // Use search result for now, enhance if needed
        setIsPreviewOpen(true);
        // If full details needed:
        // try {
        //     const fullDoc = await api.getArchiveDocumentById(doc.archiveDocumentId!, token);
        //     setPreviewingDoc(fullDoc); // Set full doc
        //     setIsPreviewOpen(true);
        // } catch { /* TODO: Toast error */ }
    };

    const handleOpenUnit = (unit: ArchiveDocumentSearchResult) => {
        navigate(`/archive?unitId=${unit.archiveDocumentId}`);
    };

     // Dialog Handlers
     const handleFormOpenChange = (open: boolean) => {
         setIsFormOpen(open);
         if (!open) { setEditingDoc(null); } // Reset on close
     };
     const handlePreviewOpenChange = (open: boolean) => {
         setIsPreviewOpen(open);
         if (!open) { setPreviewingDoc(null); } // Reset on close
     };

    // Search & Pagination Handlers
    const handleSearch = (newQuery: SearchRequest['query']) => {
         if (JSON.stringify(newQuery) !== JSON.stringify(searchQuery())) {
            setSearchQuery(newQuery); setCurrentPage(1);
         }
    };
    const handlePageChange = (newPage: number) => {
         if (newPage !== currentPage()) { setCurrentPage(newPage); }
    };

     // --- Search Fields Definition ---
     const searchFields = createMemo((): SearchFieldOption[] => {
          const fields: SearchFieldOption[] = [
              { value: 'title', label: 'Title', type: 'text' }, { value: 'creator', label: 'Creator', type: 'text' },
              { value: 'creationDate', label: 'Creation Date', type: 'text' }, { value: 'contentDescription', label: 'Description', type: 'text'},
              { value: 'isDigitized', label: 'Is Digitized', type: 'boolean'},
              { value: 'tags', label: 'Tags', type: 'tags', options: availableTags()?.map(t => ({value: t.tagId!, label: t.name})) ?? [] },
              { value: 'topographicSignatureElementIds', label: 'Topo Sig (Any ID)', type: 'text' },
              { value: 'descriptiveSignatureElementIds', label: 'Desc Sig (Any ID)', type: 'text' },
          ];
           // Add type filter only if not inside a unit
           if (parentUnitId() === null) {
                fields.push({ value: 'type', label: 'Type', type: 'select', options: [{value: 'unit', label: 'Unit'}, {value:'document', label: 'Document'}]});
           }
          if (authState.user?.role === 'admin') {
              fields.push({ value: 'active', label: 'Is Active', type: 'boolean' });
              fields.push({ value: 'ownerUserId', label: 'Owner User ID', type: 'number' });
          }
          return fields;
     });

    return (
        <div class={styles.archivePageContainer}>
            {/* Header */}
            <div class={styles.archiveHeaderContainer}>
                 <Show when={parentUnitId() !== null}>
                    <Button variant="outline" size="icon" onClick={() => navigate('/archive')} title="Back to Main Archive" class={styles.backButton}>
                        <Icon name="ArrowLeft" size="1rem" />
                    </Button>
                 </Show>
                 {/* Wrap title/desc */}
                 <div class={styles.headerTextContent}> {/* Added wrapper */}
                      <h1 class={styles.pageTitle}>
                         <span class={styles.archiveTitleContainer}>
                            <Show when={parentUnitResource()} fallback={ parentUnitId() !== null ? <LoadingSpinner size="sm"/> : <Icon name="Archive" class={styles.archiveIcon} /> }>
                                 {(parent) => <Icon name="FolderOpen" class={styles.archiveIcon} color="hsl(var(--primary))" />}
                            </Show>
                            <Show when={parentUnitResource()} fallback={'Archive'}>
                                 {(parent) => <>Unit: <span class={styles.unitTitleHighlight}>{parent().title}</span></>}
                             </Show>
                         </span>
                      </h1>
                     <p class={styles.pageDescription}>
                         {parentUnitResource() ? `Browsing items within "${parentUnitResource()!.title}".` : 'Manage archival documents and units.'}
                     </p>
                 </div>
                 {/* Create Button/Dialog Trigger (Spacer takes up remaining space) */}
                 <div style={{"flex-grow": 1}} />
                 <Dialog open={isFormOpen()} onOpenChange={handleFormOpenChange}>
                    <DialogTrigger asChild>
                        <Button onClick={handleCreateNew} class={styles.createButtonContainer}>
                            <Icon name="PlusCircle" class={styles.iconMargin}/>
                            {parentUnitId() !== null ? 'Create Document Here' : 'Create Item'}
                        </Button>
                    </DialogTrigger>
                    {/* Removed Show wrapper, Dialog handles rendering */}
                    <DialogContent size="xl"> {/* Consider larger size for this form */}
                        <DialogHeader><DialogTitle>{formDialogTitle()}</DialogTitle></DialogHeader>
                         {/* Wrap form in DialogBody for scrolling */}
                         <DialogBody>
                             <DocumentForm
                                 docToEdit={editingDoc()}
                                 onSave={handleSaveSuccess}
                                 forceType={formInitialType()}
                                 forcedParentId={formInitialParentId()}
                                 forcedParentTitle={formInitialParentTitle()}
                             />
                         </DialogBody>
                    </DialogContent>
                 </Dialog>
            </div>

            {/* Search Bar */}
            <div class={styles.searchBarContainer}>
                 <Suspense fallback={<LoadingSpinner />}>
                     <SearchBar fields={searchFields()} onSearch={handleSearch} isLoading={documentsData.loading} />
                 </Suspense>
            </div>


            {/* Document List */}
            <Card class={styles.archiveListCard}>
                <CardHeader>
                    {/* Display parent loading error here if needed */}
                    <Show when={parentUnitResource.error}>
                        <ErrorDisplay message={`Error loading parent unit: ${parentUnitResource.error?.message}`} />
                    </Show>
                     {/* Display document loading error */}
                    <Show when={documentsData.error && !parentUnitResource.error}>
                         <ErrorDisplay message={`Error loading documents: ${documentsData.error?.message}`} />
                    </Show>
                </CardHeader>
                <CardContent>
                     <Show when={documentsData.loading || parentUnitResource.loading}
                          fallback={
                            <Show when={!documentsData.error && !parentUnitResource.error && documentsData()}>
                                {(data) => ( // data() is the accessor
                                    <Show when={data().data.length > 0}
                                        fallback={<p class={styles.emptyStateText}>{searchQuery().length > 0 ? 'No items match search.' : (parentUnitId() !== null ? 'This unit is empty.' : 'Archive is empty.')}</p>}
                                    >
                                        <DocumentList
                                            documents={data().data}
                                            onEdit={handleEdit}
                                            onDisable={handleDisable}
                                            onPreview={handlePreview}
                                            onOpenUnit={handleOpenUnit}
                                        />
                                    </Show>
                                )}
                            </Show>
                          }
                     >
                         <div class={styles.loadingContainer}><LoadingSpinner size="lg" /></div>
                     </Show>

                    {/* Pagination */}
                     <Show when={!documentsData.loading && (documentsData()?.totalPages ?? 0) > 1}>
                         <div class={styles.paginationContainer}>
                             <Pagination currentPage={currentPage()} totalPages={documentsData()?.totalPages ?? 1} onPageChange={handlePageChange} />
                         </div>
                     </Show>
                </CardContent>
            </Card>

             {/* Preview Dialog */}
             <DocumentPreviewDialog
                 isOpen={isPreviewOpen()}
                 onOpenChange={handlePreviewOpenChange}
                 document={previewingDoc()}
                 onEdit={handleEdit}
                 onDisable={handleDisable}
                 parentUnitTitle={parentUnitResource()?.archiveDocumentId === previewingDoc()?.parentUnitArchiveDocumentId ? parentUnitResource()?.title : undefined}
             />
        </div>
    );
};

export default ArchivePage;

// frontend/src/components/archive/ArchivePage.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import DocumentList from './DocumentList';
import DocumentForm from './DocumentForm';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import SearchBar, { type SearchFieldOption } from '@/components/shared/SearchBar';
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
import type { Tag } from '../../../../backend/src/functionalities/tag/models';
import type { ArchiveDocument, ArchiveDocumentSearchResult } from '../../../../backend/src/functionalities/archive/document/models';
import type { SearchRequest, SearchResponse, SearchQueryElement } from '../../../../backend/src/utils/search';
import { PlusCircle } from 'lucide-react';
import { Pagination } from '@/components/shared/Pagination';
import { toast } from "sonner";
// Import Card components for layout
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { cn } from '@/lib/utils'; // Import cn

const ARCHIVE_PAGE_SIZE = 10;

const ArchivePage: React.FC = () => {
  const { token, user } = useAuth();
  const [documents, setDocuments] = useState<ArchiveDocumentSearchResult[]>([]); // Use SearchResult for list display
  const [availableTags, setAvailableTags] = useState<Tag[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [editingDoc, setEditingDoc] = useState<ArchiveDocument | null>(null); // Use base type for editing
  const [isFormOpen, setIsFormOpen] = useState(false);

   // Search & Pagination State
   const [searchQuery, setSearchQuery] = useState<SearchRequest['query']>([]);
   const [currentPage, setCurrentPage] = useState(1);
   const [pageSize, setPageSize] = useState(ARCHIVE_PAGE_SIZE);
   const [totalDocs, setTotalDocs] = useState(0);
   const [totalPages, setTotalPages] = useState(1);

  // Fetch available tags for search options
  useEffect(() => {
    const fetchTags = async () => {
        if (!token) return;
        try {
            const tags = await api.getAllTags(token);
            setAvailableTags(tags.sort((a, b) => a.name.localeCompare(b.name))); // Sort tags
        } catch (err) { console.error("Failed to fetch tags for search options:", err); }
    };
    fetchTags();
  }, [token]);


  // Combined fetch/search function with automatic filtering based on role
   const fetchDocuments = useCallback(async (page = currentPage, query = searchQuery) => {
       if (!token) return;
       setIsLoading(true); setError(null);
       try {
           let finalQuery: SearchQueryElement[] = [...query];

           // --- Default Filters based on Role ---
           const activeFilterExists = finalQuery.some(q => q.field === 'active');
           if (!activeFilterExists && user?.role !== 'admin') {
               // Regular users only see active documents by default
               finalQuery.push({ field: 'active', condition: 'EQ', value: true, not: false });
           } else if (activeFilterExists && user?.role !== 'admin') {
               // Prevent non-admins overriding the active filter
               // Add type assertion here
               finalQuery = finalQuery.map(q =>
                    q.field === 'active' ? { ...q, value: true } : q
               ) as SearchQueryElement[]; // Assert the result type
           }

           const ownerFilterExists = finalQuery.some(q => q.field === 'ownerUserId');
           if (!ownerFilterExists && user?.role !== 'admin' && user?.userId) {
               // Regular users only see their own documents by default
               finalQuery.push({ field: 'ownerUserId', condition: 'EQ', value: user.userId, not: false });
           }
           // --- End Default Filters ---

           const searchRequest: SearchRequest = {
               query: finalQuery, page: page, pageSize: pageSize,
               // sort: [{ field: 'modifiedOn', direction: 'DESC' }] // TS2353: Comment out if 'sort' is not in SearchRequest type
           };
           const response = await api.searchArchiveDocuments(searchRequest, token);
           setDocuments(response.data);
           setTotalDocs(response.totalSize);
           setTotalPages(response.totalPages);
           setCurrentPage(response.page);
       } catch (err: any) {
           const msg = err.message || 'Failed to fetch documents'; setError(msg); toast.error(msg); console.error("Fetch Error:", err);
           setDocuments([]); setTotalDocs(0); setTotalPages(1);
       } finally { setIsLoading(false); }
   }, [token, pageSize, currentPage, searchQuery, user?.role, user?.userId]); // Dependencies for fetch function

   // Trigger fetch on mount and changes
   useEffect(() => {
       fetchDocuments(currentPage, searchQuery);
   }, [fetchDocuments, currentPage, searchQuery]);


   // --- CRUD Handlers ---
   const handleEdit = (doc: ArchiveDocument) => {
      // Authorization check (owner or admin)
      if (user?.role !== 'admin' && user?.userId !== doc.ownerUserId) {
        toast.error("You can only edit items you own."); return;
      }
      setEditingDoc(doc); setIsFormOpen(true);
    };
    const handleCreateNew = () => { setEditingDoc(null); setIsFormOpen(true); };
    const handleDisable = async (docId: number) => { // Changed from 'delete' to 'disable'
        if (!token || !docId) return;
        const docToDisable = documents.find(d => d.archiveDocumentId === docId);
        if (!docToDisable) return;
        // Authorization check
        if (user?.role !== 'admin' && user?.userId !== docToDisable.ownerUserId) {
            toast.error("You are not authorized to disable this item."); return;
        }
        if (!window.confirm(`Are you sure you want to disable this ${docToDisable.type}? It will be hidden but can be recovered by an admin.`)) return;

        setError(null); setIsLoading(true);
        try {
            await api.disableArchiveDocument(docId, token);
            toast.success("Item disabled successfully.");
            // Refresh list, adjust page if needed
            const newTotalPages = Math.ceil((totalDocs - 1) / pageSize);
            const newCurrentPage = (currentPage > newTotalPages) ? Math.max(1, newTotalPages) : currentPage;
            await fetchDocuments(newCurrentPage, searchQuery);
            if (currentPage !== newCurrentPage) setCurrentPage(newCurrentPage);
        } catch (err: any) {
             const msg = err.message || 'Failed to disable item'; setError(msg); toast.error(`Disable failed: ${msg}`); console.error("Disable Error:", err);
        } finally { setIsLoading(false); }
    };
    const handleSaveSuccess = async () => {
        setIsFormOpen(false); setEditingDoc(null);
        toast.success(editingDoc ? "Document/Unit updated." : "Document/Unit created.");
        await fetchDocuments(currentPage, searchQuery); // Refresh list
    };

   // --- Search & Pagination Handlers ---
   const handleSearch = (newQuery: SearchRequest['query']) => { setSearchQuery(newQuery); setCurrentPage(1); /* Fetch triggered by useEffect */ };
   const handlePageChange = (newPage: number) => { setCurrentPage(newPage); /* Fetch triggered by useEffect */ };

   // Define fields available for searching - Use SearchFieldOption[] type
   const searchFields: SearchFieldOption[] = [
       { value: 'title', label: 'Title', type: 'text' },
       { value: 'creator', label: 'Creator', type: 'text' },
       { value: 'creationDate', label: 'Creation Date', type: 'text' }, // TODO: Improve with date picker component
       { value: 'contentDescription', label: 'Description', type: 'text'},
       { value: 'type', label: 'Type', type: 'select', options: [{value: 'unit', label: 'Unit'}, {value:'document', label: 'Document'}]},
       { value: 'isDigitized', label: 'Is Digitized', type: 'boolean'},
       // Change type to 'tags' and provide options
       {
          value: 'tags', // Backend field name for tag IDs
          label: 'Tags', // User label
          type: 'tags', // Use the new 'tags' type
          options: availableTags.map(t => ({value: t.tagId!, label: t.name})) // Map tags to options
       },
       // Use text input for signature IDs - needs ANY_OF condition and number values
       { value: 'topographicSignatureElementIds', label: 'Topo Sig (Any ID)', type: 'text' }, // Simplification: user enters comma-separated IDs
       { value: 'descriptiveSignatureElementIds', label: 'Desc Sig (Any ID)', type: 'text' }, // Simplification: user enters comma-separated IDs
   ];
    // Add 'active' and 'ownerUserId' fields only for admins
    if (user?.role === 'admin') {
        searchFields.push({ value: 'active', label: 'Is Active', type: 'boolean' });
        searchFields.push({ value: 'ownerUserId', label: 'Owner User ID', type: 'number' }); // Use number type
    }

  return (
    <div className="space-y-6"> {/* Overall page spacing */}
       {/* Header Section */}
       <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
           <div>
                <h1 className="text-2xl font-bold">Archive</h1>
                <p className='text-muted-foreground'>Manage archival documents and units.</p>
           </div>
           {/* Create Item Button & Dialog */}
           <Dialog open={isFormOpen} onOpenChange={setIsFormOpen}>
             <DialogTrigger asChild>
               <Button onClick={handleCreateNew} className='shrink-0'>
                   <PlusCircle className="mr-2 h-4 w-4" /> Create Item
               </Button>
             </DialogTrigger>
             {/* Reduced max width, DialogContent itself handles max-h and scroll */}
             <DialogContent className="max-w-3xl"> {/* Changed max-w-4xl to max-w-3xl */}
               <DialogHeader>
                 <DialogTitle>{editingDoc ? 'Edit Document/Unit' : 'Create New Document/Unit'}</DialogTitle>
               </DialogHeader>
               {/* Render form conditionally to ensure state resets */}
               {isFormOpen && <DocumentForm docToEdit={editingDoc} onSave={handleSaveSuccess} />}
             </DialogContent>
           </Dialog>
       </div>

       {/* Search Bar Section */}
       <SearchBar
           fields={searchFields}
           onSearch={handleSearch}
           isLoading={isLoading}
       />

        {/* Document List Section */}
        <Card>
             <CardHeader>
                 {/* Optional Title: <CardTitle>Archive Items</CardTitle> */}
                 {/* Error Display */}
                 {error && <ErrorDisplay message={error} />}
             </CardHeader>
             <CardContent> {/* Content area for list & pagination */}
                 {/* Loading State */}
                 {isLoading && <div className='flex justify-center py-10'><LoadingSpinner /></div>}

                 {/* List and Pagination */}
                 {!isLoading && !error && (
                   <>
                     {/* Document List Table */}
                     <DocumentList documents={documents} onEdit={handleEdit} onDisable={handleDisable} />

                      {/* Pagination */}
                      {totalPages > 1 && (
                           <div className="mt-6 flex justify-center">
                               <Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={handlePageChange} />
                           </div>
                      )}

                      {/* Empty State Messages */}
                       {documents.length === 0 && searchQuery.length > 0 && (
                          <p className="text-center text-muted-foreground pt-6">No items found matching your search criteria.</p>
                      )}
                      {documents.length === 0 && searchQuery.length === 0 && (
                         <p className="text-center text-muted-foreground pt-6">The archive is empty or you have no items. Click "Create Item" to start.</p>
                      )}
                   </>
                 )}
            </CardContent>
        </Card>
    </div>
  );
};

export default ArchivePage;
