// frontend-solid/src/components/layout/Header.tsx
import { Component, Show } from 'solid-js'; // Added Show
import { useLocation, useNavigate } from '@solidjs/router';
import { useAuth } from '@/context/AuthContext';
import { Icon } from '@/components/shared/Icon';
import styles from './Header.module.css'; // Import CSS Module (Typed)
import { Button } from '@/components/ui/Button';
import { cn } from '@/lib/utils'; // Import cn

// Function to derive title from pathname (simple version)
const getTitleFromPath = (pathname: string): string => {
    const segments = pathname.split('/').filter(Boolean);
    if (segments.length === 0) return 'Dashboard';
    // Handle specific cases
    if (segments[0] === 'signatures' && segments[2] === 'elements') {
        return 'Signature Elements'; // More specific title
    }
    const title = segments[0].replace(/-/g, ' ');
    // Capitalize first letter
    return title.charAt(0).toUpperCase() + title.slice(1);
};

interface HeaderProps {
    toggleSidebar?: () => void; // For potential mobile toggle
}

const Header: Component<HeaderProps> = (props) => {
    const [authState, { logout }] = useAuth();
    const location = useLocation();
    const navigate = useNavigate(); // Still potentially useful for explicit navigation

    const currentPageTitle = () => getTitleFromPath(location.pathname);

    const handleLogout = async () => {
        await logout();
        // AuthProvider change triggers route protection, navigation should be handled there
    };

    return (
        <header class={styles.headerContainer}>
            {/* Mobile Menu Button (Placeholder) */}
            <Show when={props.toggleSidebar}>
                <Button
                    variant="outline"
                    size="icon"
                    class={styles.mobileMenuButton}
                    onClick={props.toggleSidebar}
                    aria-label="Toggle Menu"
                >
                    <Icon name="Menu" />
                </Button>
            </Show>

            {/* Page Title */}
            <h1 class={styles.pageTitle}>{currentPageTitle()}</h1>

            {/* Right Section */}
            <div class={styles.rightSection}>
                <Show when={authState.user}>
                    {(user) => ( // Use accessor
                        <span class={styles.userInfo} title={`User: ${user().login} | Role: ${user().role}`}>
                            {user().login} ({user().role})
                        </span>
                    )}
                </Show>
                <Button
                    variant="outline"
                    size="icon"
                    onClick={handleLogout}
                    aria-label="Logout"
                    title="Logout"
                    class={styles.headerButton}
                >
                    <Icon name="LogOut" />
                </Button>
            </div>
        </header>
    );
};

export default Header;

// frontend/src/components/layout/Header.tsx
import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom'; // Import useLocation
import { Button } from '@/components/ui/button';
import { LogOut, Menu } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';

interface HeaderProps {
  toggleSidebar?: () => void; // For mobile potentially
}

// Function to derive title from pathname (simple example)
const getTitleFromPath = (pathname: string): string => {
    const segments = pathname.split('/').filter(Boolean); // Remove empty strings
    if (segments.length === 0) return 'Dashboard';
    const title = segments[0].replace('-', ' '); // Replace hyphens if any
    return title.charAt(0).toUpperCase() + title.slice(1); // Capitalize
};


const Header: React.FC<HeaderProps> = ({ toggleSidebar }) => {
  const { logout, user } = useAuth();
  const location = useLocation(); // Get current location
  const navigate = useNavigate();
  const currentPageTitle = getTitleFromPath(location.pathname); // Derive title

  const handleLogout = async () => {
      await logout();
      navigate('/login');
  }


  return (
    <header className="sticky top-0 z-10 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
       {toggleSidebar && (
         <Button size="icon" variant="outline" className="sm:hidden" onClick={toggleSidebar}>
           <Menu className="h-5 w-5" />
           <span className="sr-only">Toggle Menu</span>
         </Button>
       )}
       <h1 className="text-xl font-semibold">{currentPageTitle}</h1>
       <div className="ml-auto flex items-center gap-2">
           <span className="text-sm text-muted-foreground hidden sm:inline">
              {user?.login} ({user?.role})
           </span>
           <Button variant="outline" size="icon" onClick={handleLogout}>
             <LogOut className="h-4 w-4" />
             <span className="sr-only">Logout</span>
           </Button>
       </div>
    </header>
  );
};

export default Header;
