// frontend/src/components/notes/NotesPage.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import NoteList from './NoteList';
import NoteEditor from './NoteEditor';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import SearchBar, { type SearchFieldOption } from '@/components/shared/SearchBar'; // Import SearchFieldOption
import { Pagination } from '@/components/shared/Pagination';
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
import type { Note, NoteInput } from '../../../../backend/src/functionalities/note/models';
import type { Tag } from '../../../../backend/src/functionalities/tag/models';
import type { SearchRequest, SearchResponse, SearchQueryElement } from '../../../../backend/src/utils/search';
import { PlusCircle } from 'lucide-react';
import { toast } from "sonner";
// Import Card components for layout
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

const NOTES_PAGE_SIZE = 10; // Number of notes per page

const NotesPage: React.FC = () => {
  const { user, token } = useAuth();
  const [notes, setNotes] = useState<Note[]>([]);
  const [availableTags, setAvailableTags] = useState<Tag[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [editingNote, setEditingNote] = useState<Note | null>(null);
  const [isEditorOpen, setIsEditorOpen] = useState(false);

  // Search & Pagination State
  const [searchQuery, setSearchQuery] = useState<SearchRequest['query']>([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalNotes, setTotalNotes] = useState(0);
  const [totalPages, setTotalPages] = useState(1);

  // Fetch available tags for the search bar options
  useEffect(() => {
    const fetchTags = async () => {
        if (!token) return;
        try {
            const tags = await api.getAllTags(token);
            setAvailableTags(tags);
        } catch (err) {
            console.error("Failed to fetch tags for search options:", err);
            // Optionally show a toast notification
        }
    };
    fetchTags();
  }, [token]);


  // Function to fetch/search notes, ensuring owner filter
  const fetchNotes = useCallback(async (page = currentPage, query = searchQuery) => {
    if (!token || !user?.userId) return; // Need userId for filtering
    setIsLoading(true);
    setError(null);
    try {
        // Always filter by the current user's ID
        const ownerFilter: SearchQueryElement = { field: 'ownerUserId', condition: 'EQ', value: user.userId, not: false };
        const queryWithoutOwner = query.filter(q => q.field !== 'ownerUserId'); // Avoid duplication

        const searchRequest: SearchRequest = {
            query: [...queryWithoutOwner, ownerFilter],
            page: page,
            pageSize: NOTES_PAGE_SIZE,
            // Optional: Default sort order
            // sort: [{ field: 'modifiedOn', direction: 'DESC' }] // TS2353: Comment out if 'sort' is not in SearchRequest type
        };
        const response = await api.searchNotes(searchRequest, token);
        setNotes(response.data);
        setTotalNotes(response.totalSize);
        setTotalPages(response.totalPages);
        setCurrentPage(response.page);
    } catch (err: any) {
        const msg = err.message || 'Failed to fetch notes';
        setError(msg);
        toast.error(msg);
        console.error("Fetch Notes Error:", err);
        setNotes([]); // Clear data on error
        setTotalNotes(0);
        setTotalPages(1);
    } finally {
        setIsLoading(false);
    }
  }, [token, user?.userId, currentPage, searchQuery]); // Add userId dependency

  // Trigger fetchNotes on mount and when relevant state changes
  useEffect(() => {
    fetchNotes(currentPage, searchQuery);
  }, [fetchNotes, currentPage, searchQuery]);

  // --- CRUD Handlers ---
  const handleEdit = (note: Note) => {
    setEditingNote(note);
    setIsEditorOpen(true);
  };

  const handleCreateNew = () => {
    setEditingNote(null);
    setIsEditorOpen(true);
  };

   const handleDelete = async (noteId: number) => {
       if (!token || !noteId) return;

       // Check if user is admin (current backend requirement for delete)
       if (user?.role !== 'admin') {
           toast.error("Deletion currently restricted to administrators.");
           return;
       }

       if (!window.confirm("Are you sure you want to delete this note? This action cannot be undone.")) return;

       setError(null);
       setIsLoading(true); // Use main loading state during delete

       try {
           await api.deleteNote(noteId, token);
           toast.success("Note deleted successfully.");

           // Refetch notes, adjust page if necessary
           const newTotalPages = Math.ceil((totalNotes - 1) / NOTES_PAGE_SIZE);
           const newCurrentPage = (currentPage > newTotalPages) ? Math.max(1, newTotalPages) : currentPage;

           await fetchNotes(newCurrentPage, searchQuery); // Fetch potentially adjusted page
           if (currentPage !== newCurrentPage) {
                setCurrentPage(newCurrentPage); // Update local page state if changed
           }
       } catch (err: any) {
            const msg = err.message || 'Failed to delete note';
            setError(msg);
            toast.error(`Delete failed: ${msg}`);
            console.error("Delete Note Error:", err);
       } finally {
           setIsLoading(false);
       }
   };

  const handleSaveSuccess = async () => {
    setIsEditorOpen(false);
    setEditingNote(null);
    toast.success(editingNote ? "Note updated successfully." : "Note created successfully.");
    // Refresh the current page of notes
    await fetchNotes(currentPage, searchQuery);
  };

  // --- Search & Pagination Handlers ---
  const handleSearch = (newQuery: SearchRequest['query']) => {
      setSearchQuery(newQuery);
      setCurrentPage(1); // Reset to first page on new search
      // fetchNotes triggered by useEffect
  };

  const handlePageChange = (newPage: number) => {
      setCurrentPage(newPage);
      // fetchNotes triggered by useEffect
  };

  // Define fields for the SearchBar
  // Use SearchFieldOption[] type explicitly
  const searchFields: SearchFieldOption[] = [
      { value: 'title', label: 'Title', type: 'text' },
      { value: 'content', label: 'Content', type: 'text' },
      { value: 'shared', label: 'Is Shared', type: 'boolean' },
      // Change type to 'tags' and provide options
      {
        value: 'tags', // Field name the backend expects for tag ID search
        label: 'Tags', // User-facing label
        type: 'tags', // Use the new 'tags' type
        options: availableTags.map(t => ({value: t.tagId!, label: t.name})) // Map tags to options { value: id, label: name }
      },
  ];

  return (
    <div className="space-y-6"> {/* Overall page spacing */}
        {/* Header Section */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
                 <h1 className="text-2xl font-bold">My Notes</h1>
                 <p className='text-muted-foreground'>Create, view, and manage your personal notes.</p>
            </div>
            {/* Create Note Button and Dialog */}
            <Dialog open={isEditorOpen} onOpenChange={setIsEditorOpen}>
            <DialogTrigger asChild>
                <Button onClick={handleCreateNew} className='shrink-0'>
                    <PlusCircle className="mr-2 h-4 w-4" /> Create Note
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[600px]">
                <DialogHeader>
                <DialogTitle>{editingNote ? 'Edit Note' : 'Create New Note'}</DialogTitle>
                </DialogHeader>
                {/* Render editor only when dialog is open to ensure fresh state/fetch */}
                {isEditorOpen && <NoteEditor noteToEdit={editingNote} onSave={handleSaveSuccess} />}
            </DialogContent>
            </Dialog>
        </div>

       {/* Search Bar Section */}
       <SearchBar
           fields={searchFields}
           onSearch={handleSearch}
           isLoading={isLoading}
       />

        {/* Notes List Section */}
        <Card>
            <CardHeader>
                 {/* Optional: Title like "Notes List" could go here */}
                 {/* Error display inside the card header */}
                 {error && <ErrorDisplay message={error} />}
            </CardHeader>
            <CardContent> {/* Content area for list and pagination */}
                {/* Loading State */}
                {isLoading && <div className="flex justify-center py-10"><LoadingSpinner /></div>}

                {/* List and Pagination */}
                {!isLoading && !error && (
                    <>
                    {/* Note List Table */}
                    <NoteList notes={notes} onEdit={handleEdit} onDelete={handleDelete} />

                    {/* Pagination Controls */}
                    {totalPages > 1 && (
                        <div className="mt-6 flex justify-center">
                            <Pagination
                                currentPage={currentPage}
                                totalPages={totalPages}
                                onPageChange={handlePageChange}
                            />
                        </div>
                    )}

                    {/* Empty State Messages */}
                    {notes.length === 0 && searchQuery.length > 0 && (
                        <p className="text-center text-muted-foreground pt-6">No notes found matching your search criteria.</p>
                    )}
                    {notes.length === 0 && searchQuery.length === 0 && (
                        <p className="text-center text-muted-foreground pt-6">You haven't created any notes yet. Click "Create Note" to start!</p>
                    )}
                    </>
                )}
            </CardContent>
        </Card>
    </div>
  );
};

export default NotesPage;

// frontend-solid/src/components/notes/NotesPage.tsx
import { Component, createSignal, createResource, Show, Suspense, createMemo } from 'solid-js'; // Added createMemo
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';
import type { NoteWithDetails } from '../../../../backend/src/functionalities/note/models';
import type { Tag } from '../../../../backend/src/functionalities/tag/models';
import type { SearchRequest, SearchResponse, SearchQueryElement } from '../../../../backend/src/utils/search';

import { Button } from '@/components/ui/Button';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogBody } from '@/components/ui/Dialog'; // Added DialogBody
import { Card, CardContent, CardHeader } from '@/components/ui/Card';
import NoteList from './NoteList';
import NoteEditor from './NoteEditor';
import NotePreviewDialog from './NotePreviewDialog';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import SearchBar, { type SearchFieldOption } from '@/components/shared/SearchBar'; // Import SearchBar
import { Icon } from '@/components/shared/Icon';
import { Pagination } from '@/components/shared/Pagination'; // Import Pagination
import styles from './NotesPage.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils'; // Import cn if needed

const NOTES_PAGE_SIZE = 10; // Define page size

const NotesPage: Component = () => {
    const [authState] = useAuth();
    const [editingNote, setEditingNote] = createSignal<NoteWithDetails | null>(null);
    const [previewingNote, setPreviewingNote] = createSignal<NoteWithDetails | null>(null);
    const [isEditorOpen, setIsEditorOpen] = createSignal(false);
    const [isPreviewOpen, setIsPreviewOpen] = createSignal(false);

    // State for search and pagination
    const [searchQuery, setSearchQuery] = createSignal<SearchRequest['query']>([]);
    const [currentPage, setCurrentPage] = createSignal(1);

    // Resource for available tags (for search bar options)
    const [availableTags] = createResource(
        () => authState.token,
        async (token) => {
            if (!token) return [];
            try { return await api.getAllTags(token); }
            catch { console.error("Failed to load tags for search"); return []; }
        },
        { initialValue: [] }
    );

    // Resource for notes data - depends on token, current page, and search query
    const [notesData, { refetch: refetchNotes }] = createResource(
        () => ({ token: authState.token, page: currentPage(), query: searchQuery() }), // Dependencies
        async ({ token, page, query }) => {
            if (!token) return { data: [], totalSize: 0, totalPages: 1, page: 1 }; // Default empty state
            console.log(`Fetching notes - Page: ${page}, Query:`, query);
            const searchRequest: SearchRequest = { query: query, page, pageSize: NOTES_PAGE_SIZE };
            try {
                const response = await api.searchNotes(searchRequest, token);
                return response;
            } catch (error) {
                console.error("Fetch Notes Error:", error);
                 // TODO: Handle error more gracefully (e.g., toast)
                throw error; // Propagate error to resource state
            }
        },
        { initialValue: { data: [], totalSize: 0, totalPages: 1, page: 1 } } // Initial structure
    );

    // --- CRUD Handlers ---
    const handleEdit = (note: NoteWithDetails) => {
        setEditingNote(note);
        setIsEditorOpen(true);
    };

    const handleCreateNew = () => {
        setEditingNote(null);
        setIsEditorOpen(true);
    };

    const handleDelete = async (noteId: number) => {
        const token = authState.token;
        if (!token || !noteId) { /* TODO: toast error */ return; }
        // TODO: Add check if user is owner or admin if needed based on backend policy
        if (!window.confirm("Are you sure you want to delete this note?")) return;

        try {
            await api.deleteNote(noteId, token);
            // TODO: toast success
            // Refresh data after delete - potentially adjust page if last item removed
            const currentTotal = notesData()?.totalSize ?? 0;
            const newTotal = currentTotal - 1;
            const newTotalPages = Math.max(1, Math.ceil(newTotal / NOTES_PAGE_SIZE));
            if (currentPage() > newTotalPages && newTotalPages > 0) { // Ensure newTotalPages is positive
                setCurrentPage(newTotalPages); // This will trigger refetch via resource dependency
            } else {
                refetchNotes();
            }
        } catch (err: any) {
            console.error("Delete Note Error:", err);
            // TODO: toast error
        }
    };

    const handleSaveSuccess = () => {
        setIsEditorOpen(false); // Close the dialog
        // TODO: toast success
        refetchNotes(); // Refresh the list
    };

    // --- Preview Handler ---
    const handlePreview = (note: NoteWithDetails) => {
        setPreviewingNote(note);
        setIsPreviewOpen(true);
    };

    // --- Editor Dialog Open Change ---
    const handleEditorOpenChange = (open: boolean) => {
        setIsEditorOpen(open);
        if (!open) { setEditingNote(null); } // Reset on close
    };

     // --- Preview Dialog Open Change ---
     const handlePreviewOpenChange = (open: boolean) => {
         setIsPreviewOpen(open);
         if (!open) { setPreviewingNote(null); } // Reset on close
     };

    // --- Search & Pagination Handlers ---
    const handleSearch = (newQuery: SearchRequest['query']) => {
        if (JSON.stringify(newQuery) !== JSON.stringify(searchQuery())) {
            setSearchQuery(newQuery);
            setCurrentPage(1); // Reset page on new search
        }
    };
    const handlePageChange = (newPage: number) => {
        if (newPage !== currentPage()) {
            setCurrentPage(newPage);
        }
    };

    // --- Search Fields Definition ---
    const searchFields = createMemo((): SearchFieldOption[] => {
         const fields: SearchFieldOption[] = [
             { value: 'title', label: 'Title', type: 'text' as const },
             { value: 'content', label: 'Content', type: 'text' as const },
             { value: 'shared', label: 'Is Shared', type: 'boolean' as const },
             {
               value: 'tags', label: 'Tags', type: 'tags' as const,
               // Map tag resource data to options format
               options: availableTags()?.map(t => ({value: t.tagId!, label: t.name})) ?? []
             },
         ];
         // Only allow admins to search by owner
         if (authState.user?.role === 'admin') {
              fields.push({ value: 'ownerLogin', label: 'Owner Login', type: 'text' as const });
         }
         return fields;
    });

    // Check if the resource is ready (not loading and no error)
    const isNotesDataReady = createMemo(() => !notesData.loading && !notesData.error && !!notesData());
    // Memoize the actual data array to avoid re-calculation
    const currentNotes = createMemo(() => notesData()?.data ?? []);

    return (
        <div class={styles.notesPageContainer}>
            <div class={styles.headerContainer}>
                <div class={styles.headerTextContent}>
                    <h1 class={styles.pageTitle}>Notes</h1>
                    <p class={styles.pageDescription}>Create, view, and manage personal & shared notes.</p>
                </div>
                <Dialog open={isEditorOpen()} onOpenChange={handleEditorOpenChange}>
                    <DialogTrigger asChild>
                        <Button onClick={handleCreateNew} class={styles.createButtonContainer}>
                            <Icon name="PlusCircle" class={styles.iconMargin}/> Create Note
                        </Button>
                    </DialogTrigger>
                    <DialogContent size="md">
                        <DialogHeader>
                            <DialogTitle>{editingNote() ? 'Edit Note' : 'Create New Note'}</DialogTitle>
                        </DialogHeader>
                        {/* Wrap Form in DialogBody */}
                         <DialogBody>
                            <NoteEditor noteToEdit={editingNote()} onSave={handleSaveSuccess} />
                         </DialogBody>
                    </DialogContent>
                </Dialog>
            </div>

             {/* Search Bar Component */}
             <div class={styles.searchBarContainer}>
                <Suspense fallback={<LoadingSpinner/>}> {/* Suspense for tag loading */}
                    <SearchBar fields={searchFields()} onSearch={handleSearch} isLoading={notesData.loading} />
                 </Suspense>
             </div>

            <Card class={styles.notesListCard}>
                 {/* No Header needed here */}
                <CardContent>
                     <Show when={notesData.error}>
                         <ErrorDisplay message={`Failed to load notes: ${notesData.error?.message}`} />
                     </Show>
                     <Show when={notesData.loading && !currentNotes().length}> {/* Show loader only if no data is present yet */}
                         <div class={styles.loadingContainer}>
                             <LoadingSpinner size="lg" />
                         </div>
                     </Show>
                      {/* Use memoized check for readiness */}
                      <Show when={isNotesDataReady()}>
                         {/* Access the memoized notes array */}
                         <Show when={currentNotes().length > 0}
                             fallback={<p class={styles.emptyStateText}>{searchQuery().length > 0 ? 'No notes match your search.' : 'No notes yet. Create one!'}</p>}
                         >
                             <NoteList notes={currentNotes()} onEdit={handleEdit} onDelete={handleDelete} onPreview={handlePreview} />
                         </Show>
                      </Show>

                     {/* Pagination Component */}
                     <Show when={isNotesDataReady() && (notesData()?.totalPages ?? 0) > 1}>
                         <div class={styles.paginationContainer}>
                             <Pagination
                                 currentPage={currentPage()}
                                 totalPages={notesData()?.totalPages ?? 1}
                                 onPageChange={handlePageChange}
                             />
                         </div>
                     </Show>
                </CardContent>
            </Card>

             {/* Note Preview Dialog */}
             <NotePreviewDialog
                 isOpen={isPreviewOpen()}
                 onOpenChange={handlePreviewOpenChange}
                 note={previewingNote()}
             />

        </div>
    );
};

export default NotesPage;
