// frontend-react/src/components/archive/DocumentList.tsx
import React from 'react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge'; // Only used if showing tags/status badges
// Added Eye icon for preview
import { Edit, Trash2, FileText, Folder, Eye } from 'lucide-react'; // Icons
import type { ArchiveDocument, ArchiveDocumentSearchResult } from '../../../../backend/src/functionalities/archive/document/models';
import { useAuth } from '@/hooks/useAuth';
import { cn } from '@/lib/utils';

interface DocumentListProps {
  documents: ArchiveDocumentSearchResult[]; // Use search result which includes resolved signatures
  onEdit: (doc: ArchiveDocument) => void; // Pass base type for editing simplicity
  onDisable: (docId: number) => void;
  // Added handlers for preview and opening units
  onPreview: (doc: ArchiveDocumentSearchResult) => void;
  onOpenUnit: (doc: ArchiveDocumentSearchResult) => void;
}

// Temporary type assertion if backend type is missing resolved signatures
type ArchiveDocumentSearchResultWithResolved = ArchiveDocumentSearchResult & {
    resolvedTopographicSignatures?: string[];
    resolvedDescriptiveSignatures?: string[];
};


const DocumentList: React.FC<DocumentListProps> = ({ documents, onEdit, onDisable, onPreview, onOpenUnit }) => {
  const { user } = useAuth();

  const canModify = (docOwnerId: number) => {
      return user?.role === 'admin' || user?.userId === docOwnerId;
  };

  // Handle click action based on item type
  const handleClick = (doc: ArchiveDocumentSearchResult) => {
      if (doc.type === 'unit') {
          onOpenUnit(doc);
      } else {
          onPreview(doc); // Preview document by default
      }
  };

  if (documents.length === 0) {
    return null;
  }

  return (
    <div className="border rounded-lg overflow-hidden">
        <Table>
            <TableHeader>
                <TableRow>
                    <TableHead className='w-[50px]'>Type</TableHead>
                    <TableHead>Title</TableHead>
                    <TableHead>Creator</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead className='max-w-[200px]'>Topographic Sig</TableHead>
                    <TableHead className='max-w-[200px]'>Descriptive Sig</TableHead>
                    <TableHead className="text-right w-[130px]">Actions</TableHead> {/* Increased width */}
                </TableRow>
            </TableHeader>
            <TableBody>
                {documents.map((doc) => {
                    const docWithResolved = doc as ArchiveDocumentSearchResultWithResolved;
                    const isOwnerOrAdmin = canModify(doc.ownerUserId);
                    const isUnit = doc.type === 'unit';

                    return (
                        // Make entire row clickable, but stop propagation for buttons
                        <TableRow
                           key={doc.archiveDocumentId}
                           onClick={() => handleClick(doc)}
                           className='cursor-pointer hover:bg-muted/50 transition-colors'
                           title={isUnit ? `Open Unit "${doc.title}"` : `Preview Document "${doc.title}"`}
                        >
                            <TableCell className='text-center'>
                                {isUnit
                                    ? <Folder className='h-4 w-4 text-blue-600 inline-block'/>
                                    : <FileText className='h-4 w-4 text-green-600 inline-block'/>}
                            </TableCell>
                            <TableCell className="font-medium">{doc.title}</TableCell>
                            <TableCell className="text-sm">{doc.creator}</TableCell>
                            <TableCell className="text-sm">{doc.creationDate}</TableCell>
                            <TableCell className='font-mono text-xs truncate' title={docWithResolved.resolvedTopographicSignatures?.[0] || ''}>
                                {(docWithResolved.resolvedTopographicSignatures?.[0])
                                    ? docWithResolved.resolvedTopographicSignatures[0]
                                    : <i className='text-muted-foreground not-italic'>None</i>
                                }
                            </TableCell>
                            <TableCell className='font-mono text-xs truncate' title={docWithResolved.resolvedDescriptiveSignatures?.[0] || ''}>
                                {(docWithResolved.resolvedDescriptiveSignatures?.[0])
                                    ? docWithResolved.resolvedDescriptiveSignatures[0]
                                    : <i className='text-muted-foreground not-italic'>None</i>
                                }
                            </TableCell>
                            <TableCell className="text-right space-x-1">
                                {/* Preview Button (only for documents) */}
                                {!isUnit && (
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); onPreview(doc); }} title="Preview Document">
                                        <Eye className="h-4 w-4" />
                                    </Button>
                                )}
                                {/* Edit Button (always available if permissions allow) */}
                                {isOwnerOrAdmin && (
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); onEdit(doc); }} title="Edit Item">
                                        <Edit className="h-4 w-4" />
                                    </Button>
                                )}
                                {/* Disable Button (always available if permissions allow) */}
                                {isOwnerOrAdmin && (
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); onDisable(doc.archiveDocumentId!); }} title="Disable Item">
                                        <Trash2 className="h-4 w-4 text-destructive" />
                                    </Button>
                                )}
                                {/* Read-only indicator */}
                                {!isOwnerOrAdmin && (
                                    <span className="text-xs text-muted-foreground italic pr-2">Read-only</span>
                                )}
                            </TableCell>
                        </TableRow>
                    );
                })}
            </TableBody>
        </Table>
    </div>
  );
};

export default DocumentList;

// frontend-solid/src/components/archive/DocumentList.tsx
import { Component, For, Show } from 'solid-js';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/Table";
import { Button } from '@/components/ui/Button';
import { Icon } from '@/components/shared/Icon';
import type { ArchiveDocument, ArchiveDocumentSearchResult } from '../../../../backend/src/functionalities/archive/document/models';
import { useAuth } from '@/context/AuthContext';
import { cn } from '@/lib/utils';
import styles from './DocumentList.module.css'; // Import CSS Module (Typed)

interface DocumentListProps {
    documents: ArchiveDocumentSearchResult[];
    onEdit: (doc: ArchiveDocument) => void;
    onDisable: (docId: number) => void;
    onPreview: (doc: ArchiveDocumentSearchResult) => void;
    onOpenUnit: (doc: ArchiveDocumentSearchResult) => void;
}

// Type assertion helper if needed (backend types might be out of sync)
type DocWithResolved = ArchiveDocumentSearchResult & {
    resolvedTopographicSignatures?: string[];
    resolvedDescriptiveSignatures?: string[];
};

const DocumentList: Component<DocumentListProps> = (props) => {
    const [authState] = useAuth();
    const currentUserId = () => authState.user?.userId;
    const isAdmin = () => authState.user?.role === 'admin';

    const canModify = (docOwnerId: number) => {
        return isAdmin() || currentUserId() === docOwnerId;
    };

    const handleClick = (doc: ArchiveDocumentSearchResult) => {
        if (doc.type === 'unit') {
            props.onOpenUnit(doc);
        } else {
            props.onPreview(doc); // Default to preview for documents
        }
    };

    return (
        // No outer div needed, Table handles its container
        <Table class={styles.documentListTable}>
            <TableHeader>
                <TableRow>
                    <TableHead class={styles.typeIconCell}>Type</TableHead>
                    <TableHead>Title</TableHead>
                    <TableHead>Creator</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>Topographic Sig</TableHead>
                    <TableHead>Descriptive Sig</TableHead>
                    <TableHead class={cn(styles.actionsCell, styles.documentActionsCell)}>Actions</TableHead> {/* Combine styles */}
                </TableRow>
            </TableHeader>
            <TableBody>
                <For each={props.documents}>
                    {(doc) => {
                        const isUnit = doc.type === 'unit';
                        const isOwnerOrAdmin = () => canModify(doc.ownerUserId);
                        // Cast for potentially resolved signatures (use optional chaining)
                        const docResolved = doc as DocWithResolved;

                        return (
                            <TableRow
                                onClick={() => handleClick(doc)}
                                class={styles.clickableRow}
                                title={isUnit ? `Open Unit "${doc.title}"` : `Preview Document "${doc.title}"`}
                            >
                                <TableCell class={styles.typeIconCell}>
                                    <Icon
                                        name={isUnit ? 'Folder' : 'FileText'}
                                        class={styles.typeIcon}
                                        style={{ color: isUnit ? 'var(--color-primary)' : 'hsl(145 63% 40%)' }} // Use CSS variable or HSL
                                    />
                                </TableCell>
                                <TableCell class={styles.documentTitleCell}>{doc.title}</TableCell>
                                <TableCell class={styles.mutedTextCell}>{doc.creator}</TableCell>
                                <TableCell class={styles.mutedTextCell}>{doc.creationDate}</TableCell>
                                <TableCell class={styles.signatureCell} title={docResolved.resolvedTopographicSignatures?.[0] || ''}>
                                    {docResolved.resolvedTopographicSignatures?.[0] || <i class={styles.noSignatureText}>None</i>}
                                </TableCell>
                                <TableCell class={styles.signatureCell} title={docResolved.resolvedDescriptiveSignatures?.[0] || ''}>
                                     {docResolved.resolvedDescriptiveSignatures?.[0] || <i class={styles.noSignatureText}>None</i>}
                                </TableCell>
                                <TableCell class={cn(styles.actionsCell, styles.documentActionsCell)}> {/* Combine styles */}
                                     {/* Preview Button (only for documents) */}
                                     <Show when={!isUnit}>
                                        <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); props.onPreview(doc); }} title="Preview Document">
                                            <Icon name="Eye" size="1rem" />
                                        </Button>
                                    </Show>
                                    {/* Edit/Disable Buttons (if permissions allow) */}
                                    <Show when={isOwnerOrAdmin()}
                                        fallback={<span class={styles.readOnlyText}>Read-only</span>}
                                    >
                                        <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); props.onEdit(doc as ArchiveDocument); }} title="Edit Item">
                                            <Icon name="Edit" size="1rem" />
                                        </Button>
                                        <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); props.onDisable(doc.archiveDocumentId!); }} title="Disable Item">
                                            <Icon name="Trash2" size="1rem" class={styles.textDestructive} /> {/* Use utility class */}
                                        </Button>
                                    </Show>
                                </TableCell>
                            </TableRow>
                        );
                    }}
                </For>
            </TableBody>
        </Table>
    );
};

export default DocumentList;
