// frontend-solid/src/components/notes/NoteEditor.tsx
import { Component, createSignal, createEffect, Show, createMemo, JSX } from 'solid-js';
// Removed @modular-forms/solid imports
import { z, ZodIssue } from 'zod';
import { noteFormSchema, NoteFormData } from '@/lib/zodSchemas';
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';
import type { NoteInput, NoteWithDetails } from '../../../../backend/src/functionalities/note/models';

import { Button } from '@/components/ui/Button';
import { Input, type InputProps } from '@/components/ui/Input';
import { FormLabel } from '@/components/ui/FormLabel';
import { Textarea, type TextareaProps } from '@/components/ui/Textarea';
import { Checkbox } from '@/components/ui/Checkbox';
import TagSelector from '@/components/shared/TagSelector';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import styles from './NoteEditor.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils';

interface NoteEditorProps {
    noteToEdit: NoteWithDetails | null;
    onSave: () => void; // Callback after successful save
}

const NoteEditor: Component<NoteEditorProps> = (props) => {
    const [authState] = useAuth();
    const [apiError, setApiError] = createSignal<string | null>(null);
    const [isSubmitting, setIsSubmitting] = createSignal(false);

    // Form state signals
    const [title, setTitle] = createSignal('');
    const [content, setContent] = createSignal<string | null>(null);
    const [shared, setShared] = createSignal(false);
    const [selectedTagIds, setSelectedTagIds] = createSignal<number[]>([]); // TagSelector manages this
    const [formErrors, setFormErrors] = createSignal<Partial<Record<keyof NoteFormData, string>>>({});

    // REMOVED hasErrors check

    // Sync form state when noteToEdit prop changes
    createEffect(() => {
        const note = props.noteToEdit;
        setTitle(note?.title ?? '');
        setContent(note?.content ?? null);
        setShared(note?.shared ?? false);
        setSelectedTagIds(note?.tags?.map(t => t.tagId!) ?? []);
        setApiError(null); // Clear errors when switching notes
        setFormErrors({}); // Clear validation errors
        setIsSubmitting(false); // Reset submitting state
    });

    const canEditShared = createMemo(() => {
         const note = props.noteToEdit;
         const user = authState.user;
         if (!user) return false;
         if (user.role === 'admin') return true;
         if (!note) return true; // Creating new note
         return note.ownerUserId === user.userId;
    });

    // Validation function
    const validateForm = (): boolean => {
        setFormErrors({}); // Clear previous errors
        const formData = {
            title: title(),
            content: content(),
            shared: shared(),
            tagIds: selectedTagIds(),
        };
        const result = noteFormSchema.safeParse(formData);
        if (!result.success) {
            const errors: Partial<Record<keyof NoteFormData, string>> = {};
            result.error.errors.forEach((err: ZodIssue) => {
                if (err.path.length > 0) {
                    errors[err.path[0] as keyof NoteFormData] = err.message;
                }
            });
            setFormErrors(errors);
            return false;
        }
        return true;
    };

    const handleSubmit = async (event: Event) => {
        event.preventDefault();
        const token = authState.token;
        if (!token || !validateForm()) { // Validate on submit
            setApiError("Authentication required or form invalid.");
            return;
        }
        setApiError(null);
        setIsSubmitting(true);

        const payload: Partial<NoteInput> & Pick<NoteInput, 'title' | 'tagIds'> = {
            title: title(),
            content: content() ?? '', // Use nullish coalescing
            tagIds: selectedTagIds(), // Use tag IDs from the TagSelector state
        };
        if (canEditShared()) {
            payload.shared = shared() ?? false;
        }

        try {
            if (props.noteToEdit?.noteId) {
                await api.updateNote(props.noteToEdit.noteId, payload as NoteInput, token);
            } else {
                await api.createNote(payload as NoteInput, token);
            }
            props.onSave();
        } catch (err: any) {
            const msg = err.message || 'Failed to save note';
            setApiError(msg);
            console.error("Save Note Error:", err);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <form onSubmit={handleSubmit} class={styles.noteEditorContainer}>
            <Show when={apiError()}>
                {(err) => <ErrorDisplay message={err()} />}
            </Show>
            <Show when={isSubmitting()}>
                <div class={styles.loadingOverlay}><LoadingSpinner /></div>
            </Show>

            {/* Title Input */}
            <div class={styles.formGroup}>
                <FormLabel for="note-title" required invalid={!!formErrors().title}>Title</FormLabel>
                <Input
                    id="note-title"
                    value={title()}
                    // --- FIX: Removed validateForm() call ---
                    onInput={(e) => { setTitle(e.currentTarget.value); }}
                    required
                    aria-invalid={!!formErrors().title}
                    aria-errormessage="note-title-error"
                />
                <Show when={formErrors().title}><p id="note-title-error" class={styles.errorMessage}>{formErrors().title}</p></Show>
            </div>

            {/* Content Textarea */}
            <div class={styles.formGroup}>
                <FormLabel for="note-content" invalid={!!formErrors().content}>Content</FormLabel>
                <Textarea
                    id="note-content"
                    value={content() ?? ''}
                    // --- FIX: Removed validateForm() call ---
                    onInput={(e) => { setContent(e.currentTarget.value || null); }}
                    aria-invalid={!!formErrors().content}
                    aria-errormessage="note-content-error"
                    rows={8}
                />
                <Show when={formErrors().content}><p id="note-content-error" class={styles.errorMessage}>{formErrors().content}</p></Show>
            </div>

            {/* Tag Selector */}
            <div class={styles.formGroup}>
                 <FormLabel>Tags</FormLabel>
                 <TagSelector
                     selectedTagIds={selectedTagIds()}
                     onChange={setSelectedTagIds} // Directly use the signal setter
                     disabled={isSubmitting()}
                 />
                 {/* Direct form error for tags (if schema had it) */}
                 <Show when={formErrors().tagIds}><p class={styles.errorMessage}>{formErrors().tagIds}</p></Show>
             </div>

            {/* Shared Checkbox */}
            <div class={styles.sharedCheckboxContainer}>
                <Checkbox
                    id="note-shared"
                    checked={shared()}
                    // --- FIX: Removed validateForm() call ---
                    onCheckedChange={(checked) => setShared(!!checked)} // Ensure boolean
                    disabled={!canEditShared() || isSubmitting()}
                    aria-invalid={!!formErrors().shared}
                    aria-errormessage="note-shared-error"
                />
                 <FormLabel for="note-shared" class={styles.checkboxLabel}>Share this note publicly</FormLabel>
            </div>
            {/* Show error for shared field if any */}
            <Show when={formErrors().shared}><p id="note-shared-error" class={styles.errorMessage}>{formErrors().shared}</p></Show>

            <div class={styles.formActions}>
                 {/* --- FIX: Simplified disabled check --- */}
                <Button type="submit" disabled={isSubmitting()}>
                     <Show when={isSubmitting()} fallback={props.noteToEdit ? 'Update Note' : 'Create Note'}>
                        <LoadingSpinner size="sm" class={styles.iconMargin}/> Saving...
                    </Show>
                </Button>
            </div>
        </form>
    );
};

export default NoteEditor;

// frontend-react/src/components/notes/NoteEditor.tsx
import React, { useEffect, useState } from 'react';
import { useForm, Controller } from 'react-hook-form'; // Import Controller
import { zodResolver } from '@hookform/resolvers/zod';
import { noteFormSchema } from '@/lib/zodSchemas'; // Keep type import if needed elsewhere, but rely on inference for useForm
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import TagSelector from '@/components/shared/TagSelector';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
// Import backend types Note and NoteInput
import type { Note, NoteInput, NoteWithDetails } from '../../../../backend/src/functionalities/note/models';
import { toast } from "sonner";
import { cn } from '@/lib/utils'; // Import cn
import { z } from 'zod'; // Import z for inferring type in onSubmit

// Infer the form data type directly from the schema
type NoteFormData = z.infer<typeof noteFormSchema>;

interface NoteEditorProps {
  noteToEdit: NoteWithDetails | null; // Use NoteWithDetails which includes tags/owner
  onSave: () => void; // Callback after successful save
}

const NoteEditor: React.FC<NoteEditorProps> = ({ noteToEdit, onSave }) => {
  const { token, user } = useAuth(); // Get current user
  const [isLoading, setIsLoading] = useState(false);
  const [isFetchingDetails, setIsFetchingDetails] = useState(false); // Separate loading state
  const [error, setError] = useState<string | null>(null);
  const [selectedTagIds, setSelectedTagIds] = useState<number[]>([]);

  // Check if the current user is the owner of the note being edited
  // Handle case where noteToEdit might be null during initial render or creation
  const isOwner = noteToEdit ? noteToEdit.ownerUserId === user?.userId : false;
  // Check if the current user is an admin
  const isAdmin = user?.role === 'admin';

  const { register, handleSubmit, reset, control, setValue, watch, formState: { errors } } = useForm({ // Remove explicit type here
    resolver: zodResolver(noteFormSchema),
    defaultValues: {
      title: '',
      content: '',
      shared: false, // Default to false
      tagIds: [],
    },
  });

   // Populate form when noteToEdit changes or on initial load
   useEffect(() => {
       const fetchFullNoteDetails = async (noteId: number) => {
           if (!token) return;
           setIsFetchingDetails(true); // Indicate details are loading
           setError(null);
           try {
               // Use the existing note data if available (already includes tags/ownerLogin)
               // Otherwise, fetch fresh (though list should have provided it)
               const fullNote = noteToEdit?.noteId === noteId ? noteToEdit : await api.getNoteById(noteId, token);
               const tagIds = fullNote.tags?.map(t => t.tagId!) ?? [];

               console.log("NoteEditor: Populating form with fetched 'shared' value:", fullNote.shared); // Log the value being set

               reset({
                   title: fullNote.title || '',
                   content: fullNote.content || '', // Use default value if content is null/undefined
                   shared: Boolean(fullNote.shared), // Ensure it's explicitly boolean
                   tagIds: tagIds,
               });
               setSelectedTagIds(tagIds); // Sync TagSelector state
           } catch (err: any) {
                const msg = err.message || "Failed to load note details";
                setError(msg);
                toast.error(msg);
                console.error("Fetch Note Details Error:", err);
                // Reset to potentially stale data from list or defaults
                reset({
                     title: noteToEdit?.title || '',
                     content: noteToEdit?.content || '',
                     shared: Boolean(noteToEdit?.shared), // Ensure boolean
                     tagIds: noteToEdit?.tags?.map(t => t.tagId!) ?? [],
                 });
                 setSelectedTagIds(noteToEdit?.tags?.map(t => t.tagId!) ?? []);
           } finally {
               setIsFetchingDetails(false);
           }
       };

       if (noteToEdit?.noteId) {
           fetchFullNoteDetails(noteToEdit.noteId);
       } else {
           // Reset form for creation
           reset({ title: '', content: '', shared: false, tagIds: [] });
           setSelectedTagIds([]);
           setError(null); // Clear any previous errors
           setIsFetchingDetails(false); // Not fetching details for new note
       }
   }, [noteToEdit, reset, token]);


  // Update form's tagIds when TagSelector changes
  useEffect(() => {
    setValue('tagIds', selectedTagIds);
  }, [selectedTagIds, setValue]);

  // Use the inferred type for 'data'
  const onSubmit = async (data: NoteFormData) => {
    if (!token) return;
    setIsLoading(true);
    setError(null);

    // Construct the payload according to the NoteInput interface
    const payload: NoteInput = {
        title: data.title,
        content: data.content ?? '', // Ensure content is string, even if undefined/null in form data
        shared: Boolean(data.shared), // Ensure shared is boolean
        tagIds: selectedTagIds, // Ensure the latest state is included
    };

    // Backend handles authorization for shared field, but we disable UI element below

    try {
      if (noteToEdit?.noteId) {
        // Pass the correctly typed payload
        await api.updateNote(noteToEdit.noteId, payload, token);
      } else {
        // Pass the correctly typed payload
        await api.createNote(payload, token);
      }
      onSave(); // Call the success callback (which handles toast and closing)
    } catch (err: any) {
      const msg = err.message || 'Failed to save note';
      setError(msg);
      toast.error(`Error saving note: ${msg}`);
      console.error("Save Note Error:", err);
    } finally {
      setIsLoading(false);
    }
  };

  // Show main loading spinner only when fetching details for editing
  if (isFetchingDetails) {
      return <div className="flex justify-center items-center p-10"><LoadingSpinner /></div>;
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="grid gap-4 py-4 relative">
        {/* Display fetch/save errors */}
        {error && <ErrorDisplay message={error} className="mb-4" />}
        {/* Overlay spinner during save operation */}
        {isLoading && <div className='absolute inset-0 bg-background/50 flex items-center justify-center z-10 rounded-md'><LoadingSpinner/></div>}

      <div className="grid gap-1.5"> {/* Adjusted gap */}
        <Label htmlFor="title">Title</Label>
        <Input id="title" {...register('title')} aria-invalid={errors.title ? "true" : "false"} className={cn(errors.title && "border-destructive")}/>
        {errors.title && <p className="text-xs text-destructive">{errors.title.message}</p>}
      </div>

      <div className="grid gap-1.5"> {/* Adjusted gap */}
        <Label htmlFor="content">Content</Label>
        <Textarea id="content" {...register('content')} rows={6} aria-invalid={errors.content ? "true" : "false"} className={cn(errors.content && "border-destructive")}/>
        {errors.content && <p className="text-xs text-destructive">{errors.content?.message}</p>}
      </div>

       <div className="grid gap-1.5"> {/* Adjusted gap */}
         <Label htmlFor="tags">Tags</Label>
         <TagSelector selectedTagIds={selectedTagIds} onChange={setSelectedTagIds} />
         {/* Hidden input registered with RHF for validation */}
         <input type="hidden" {...register('tagIds')} />
          {errors.tagIds && <p className="text-xs text-destructive">{typeof errors.tagIds.message === 'string' ? errors.tagIds.message : 'Invalid tag selection'}</p>}
       </div>

        {/* Use Controller for Shadcn Checkbox */}
       <div className="flex items-center space-x-2 pt-2"> {/* Added padding top */}
           <Controller
                name="shared"
                control={control}
                render={({ field: { onChange, onBlur, value, name, ref } }) => ( // Destructure field props
                     <Checkbox
                         id="shared"
                         // Ensure 'checked' prop receives a boolean
                         checked={Boolean(value)}
                         // Pass the boolean value directly to onChange handler
                         onCheckedChange={(checked) => onChange(Boolean(checked))}
                         onBlur={onBlur} // Pass onBlur
                         name={name} // Pass name
                         ref={ref} // Pass ref
                         aria-invalid={errors.shared ? "true" : "false"}
                         className={cn(errors.shared && "border-destructive")}
                         // Disable checkbox if user is not the owner AND not an admin
                         disabled={!isOwner && !isAdmin}
                         title={(!isOwner && !isAdmin) ? "Only the owner or an admin can change the shared status" : undefined}
                     />
                 )}
           />
          <Label
             htmlFor="shared"
             className={cn(
                 'cursor-pointer font-normal',
                 (!isOwner && !isAdmin) && 'cursor-not-allowed opacity-70' // Style label when disabled
             )}
           >
             Share this note publicly
          </Label>
        </div>
         {errors.shared && <p className="text-xs text-destructive">{errors.shared.message}</p>}


      <Button type="submit" disabled={isLoading || isFetchingDetails} className="mt-4 justify-self-start"> {/* Align button left */}
        {isLoading ? <LoadingSpinner size="sm" className='mr-2' /> : (noteToEdit ? 'Update Note' : 'Create Note')}
      </Button>
    </form>
  );
};

export default NoteEditor;
