// frontend/src/components/signatures/ComponentList.tsx
import React from 'react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Edit, Trash2, ListRestart } from 'lucide-react';
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';
import { useAuth } from '@/hooks/useAuth';
import { cn } from '@/lib/utils';

interface ComponentListProps {
    components: SignatureComponent[];
    selectedComponentId: number | null;
    onEdit: (component: SignatureComponent) => void;
    onDelete: (componentId: number) => void;
    onSelect: (component: SignatureComponent | null) => void; // Allow deselection
    onReindex: (componentId: number) => void;
}

const ComponentList: React.FC<ComponentListProps> = ({
    components, selectedComponentId, onEdit, onDelete, onSelect, onReindex
}) => {
    const { user } = useAuth();
    const isAdmin = user?.role === 'admin';

    // Handle row click for selection/deselection
    const handleRowClick = (component: SignatureComponent) => {
        if (selectedComponentId === component.signatureComponentId) {
            onSelect(null); // Deselect if clicking the already selected row
        } else {
            onSelect(component); // Select the clicked row
        }
    };

    // Map index types to readable labels
    const indexTypeLabels: Record<string, string> = {
        dec: 'Decimal (1, 2)',
        roman: 'Roman (I, II)',
        small_char: 'Letters (a, b)',
        capital_char: 'Capital Letters (A, B)'
    };

    // Return null if list is empty (parent handles empty message)
    if (components.length === 0) {
        return null;
    }

    return (
        // Wrap in div for border and overflow
        <div className="border rounded-lg overflow-hidden">
            <Table>
                <TableHeader>
                    <TableRow>
                        <TableHead>Name</TableHead>
                        <TableHead>Description</TableHead>
                        <TableHead>Index Type</TableHead>
                        {/* Header for element count */}
                        <TableHead className='text-center w-[100px]'>Elements</TableHead>
                        {/* Actions column only for admins */}
                        {isAdmin && <TableHead className="text-right w-[150px]">Actions</TableHead>}
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {components.map((component) => (
                        <TableRow
                            key={component.signatureComponentId}
                            onClick={() => handleRowClick(component)}
                            // Apply styles for hover, selection, and cursor
                            className={cn(
                                "cursor-pointer hover:bg-muted/50 transition-colors",
                                selectedComponentId === component.signatureComponentId && "bg-muted hover:bg-muted" // Highlight selected row
                            )}
                            aria-selected={selectedComponentId === component.signatureComponentId}
                        >
                            <TableCell className="font-medium">{component.name}</TableCell>
                            {/* Truncate description, show placeholder */}
                            <TableCell className='text-sm text-muted-foreground max-w-xs truncate' title={component.description || ''}>
                                {component.description || <i className='not-italic'>None</i>}
                            </TableCell>
                            {/* Display index type as a badge */}
                            <TableCell><Badge variant="outline">{indexTypeLabels[component.index_type] || component.index_type}</Badge></TableCell>
                            {/* Display element count */}
                            <TableCell className="text-center">{component.index_count ?? 0}</TableCell>
                            {/* Admin Actions */}
                            {isAdmin && (
                                <TableCell className="text-right space-x-1">
                                    {/* Stop propagation on button clicks to prevent row selection */}
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); onReindex(component.signatureComponentId!); }} title="Re-index Elements">
                                        <ListRestart className="h-4 w-4" />
                                    </Button>
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); onEdit(component); }} title="Edit Component">
                                        <Edit className="h-4 w-4" />
                                    </Button>
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); onDelete(component.signatureComponentId!); }} title="Delete Component">
                                        <Trash2 className="h-4 w-4 text-destructive" />
                                    </Button>
                                </TableCell>
                            )}
                        </TableRow>
                    ))}
                </TableBody>
            </Table>
        </div>
    );
};

export default ComponentList;

// frontend-solid/src/components/signatures/ComponentList.tsx
import { Component, For, Show } from 'solid-js';
import { useNavigate } from '@solidjs/router';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/Table";
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { Icon } from '@/components/shared/Icon';
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';
import { useAuth } from '@/context/AuthContext';
import styles from './ComponentList.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils'; // Import cn

interface ComponentListProps {
    components: SignatureComponent[];
    onEdit: (component: SignatureComponent) => void;
    onDelete: (componentId: number) => void;
    onReindex: (componentId: number) => void;
}

const ComponentList: Component<ComponentListProps> = (props) => {
    const [authState] = useAuth();
    const navigate = useNavigate();
    const isAdmin = () => authState.user?.role === 'admin';

    const handleRowClick = (component: SignatureComponent) => {
        navigate(`/signatures/${component.signatureComponentId}/elements`);
    };

    // Map index types to readable labels
    const indexTypeLabels: Record<string, string> = {
        dec: 'Decimal (1, 2)',
        roman: 'Roman (I, II)',
        small_char: 'Letters (a, b)',
        capital_char: 'Capitals (A, B)' // Shortened for space
    };

    return (
        <Table>
            <TableHeader>
                <TableRow>
                    <TableHead>Name</TableHead>
                    <TableHead>Description</TableHead>
                    <TableHead>Index Type</TableHead>
                    <TableHead class={styles.indexCountCell}>Elements</TableHead>
                    {/* Actions only shown to admin */}
                    <TableHead class={styles.actionsCell}>Actions</TableHead>
                </TableRow>
            </TableHeader>
            <TableBody>
                <For each={props.components}>
                    {(component) => (
                        <TableRow
                            onClick={() => handleRowClick(component)}
                            class={styles.clickableRow}
                            title={`Open elements for "${component.name}"`}
                        >
                            <TableCell class={styles.componentNameCell}>
                                <Icon name="Folder" class={styles.componentIcon} />
                                {component.name}
                            </TableCell>
                            <TableCell class={styles.descriptionCell} title={component.description || ''}>
                                <span class={!component.description ? styles.noDescriptionText : undefined}>
                                    {component.description || 'None'}
                                </span>
                            </TableCell>
                            <TableCell><Badge variant="outline">{indexTypeLabels[component.index_type] || component.index_type}</Badge></TableCell>
                            <TableCell class={styles.indexCountCell}>{component.index_count ?? 0}</TableCell>
                            <TableCell class={styles.actionsCell}>
                                <Show when={isAdmin()} fallback={<span class={styles.readOnlyText}>Read-only</span>}>
                                     <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); props.onReindex(component.signatureComponentId!); }} title="Re-index Elements">
                                        <Icon name="ListRestart" size="1rem" />
                                    </Button>
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); props.onEdit(component); }} title="Edit Component">
                                        <Icon name="Edit" size="1rem" />
                                    </Button>
                                    <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); props.onDelete(component.signatureComponentId!); }} title="Delete Component">
                                        <Icon name="Trash2" size="1rem" class={styles.textDestructive} />
                                    </Button>
                                </Show>
                            </TableCell>
                        </TableRow>
                    )}
                </For>
            </TableBody>
        </Table>
    );
};

export default ComponentList;
