// frontend-react/src/components/signatures/ElementForm.tsx
import React, { useEffect, useState } from 'react';
import { useForm, Controller, SubmitHandler } from 'react-hook-form'; // Added SubmitHandler
import { zodResolver } from '@hookform/resolvers/zod';
import { elementFormSchema } from '@/lib/zodSchemas'; // Use correct schema import, rely on inference for useForm
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import ElementSelector from './ElementSelector'; // Corrected import path
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
import type { SignatureElement, CreateSignatureElementInput, UpdateSignatureElementInput } from '../../../../backend/src/functionalities/signature/element/models'; // Import backend input types
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';
import { toast } from "sonner";
import { cn } from '@/lib/utils'; // Import cn
import { Badge } from '@/components/ui/badge'; // Import Badge
import { z } from 'zod'; // Import z for inferring type in onSubmit

// Infer the form data type directly from the schema
type ElementFormData = z.infer<typeof elementFormSchema>;

interface ElementFormProps {
    elementToEdit: SignatureElement | null;
    currentComponent: SignatureComponent;
    // Modified onSave signature to pass back the saved element or null
    onSave: (savedElement: SignatureElement | null) => void;
}

const ElementForm: React.FC<ElementFormProps> = ({ elementToEdit, currentComponent, onSave }) => {
    const { token } = useAuth();
    const [isLoading, setIsLoading] = useState(false); // For save operation
    const [isFetchingDetails, setIsFetchingDetails] = useState(false); // For loading parents
    const [error, setError] = useState<string | null>(null);
    const [selectedParentIds, setSelectedParentIds] = useState<number[]>([]);


    const { register, handleSubmit, reset, control, setValue, formState: { errors } } = useForm({ // Remove explicit type here
        resolver: zodResolver(elementFormSchema),
        defaultValues: {
            name: '',
            description: '',
            index: '', // Use empty string as default for nullable string
            parentIds: [],
        },
    });

     // Fetch parent IDs and populate form when editing
     useEffect(() => {
        const fetchParentsAndPopulate = async () => {
            if (elementToEdit?.signatureElementId && token) {
                 setIsFetchingDetails(true);
                 setError(null);
                try {
                    // Fetch element details including parent IDs
                    const fullElement = await api.getSignatureElementById(elementToEdit.signatureElementId, ['parents'], token);
                    const parentIds = fullElement.parentElements?.map(p => p.signatureElementId!) ?? [];

                    reset({
                         name: fullElement.name || '',
                         description: fullElement.description || '',
                         index: fullElement.index || '', // Use fetched index
                         parentIds: parentIds, // Populate RHF state too
                     });
                    setSelectedParentIds(parentIds); // Sync local state for selector
                } catch (err: any) {
                    const msg = err.message || "Failed to load element details";
                    setError(msg); toast.error(msg); console.error("Fetch Element Parents Error:", err);
                     reset({
                         name: elementToEdit?.name || '',
                         description: elementToEdit?.description || '',
                         index: elementToEdit?.index || '',
                         parentIds: [],
                     });
                     setSelectedParentIds([]);
                } finally {
                    setIsFetchingDetails(false);
                }

            } else {
                reset({ name: '', description: '', index: '', parentIds: [] });
                setSelectedParentIds([]); setError(null); setIsFetchingDetails(false);
            }
        };
        fetchParentsAndPopulate();
     }, [elementToEdit, reset, token]);


     // Update RHF's parentIds when the selector state changes (for validation)
     useEffect(() => {
        setValue('parentIds', selectedParentIds);
     }, [selectedParentIds, setValue]);

    // Use the inferred type for 'data'
    // Renamed from onSubmit to avoid conflict with form prop, though not strictly necessary here
    const handleFormSubmit: SubmitHandler<ElementFormData> = async (data) => {
        if (!token || !currentComponent.signatureComponentId) {
            setError("Component context is missing.");
            return;
        }
        setIsLoading(true);
        setError(null);
        let savedElementResult: SignatureElement | null = null; // To store the result

        // Prepare payloads based on backend input types
        const basePayload = {
             name: data.name,
             description: data.description ?? undefined, // Send undefined if null/empty
             // Send index only if it's not an empty string, otherwise let backend auto-generate
             index: data.index?.trim() ? data.index.trim() : undefined,
             parentIds: selectedParentIds,
        };

        const createPayload: CreateSignatureElementInput = {
            ...basePayload,
            signatureComponentId: currentComponent.signatureComponentId!,
        };

        const updatePayload: UpdateSignatureElementInput = {
            // Only send fields that might have changed
            ...(data.name !== elementToEdit?.name && { name: data.name }),
            ...(data.description !== elementToEdit?.description && { description: data.description ?? null }), // send null to clear
            ...(data.index !== elementToEdit?.index && { index: data.index?.trim() ? data.index.trim() : null }), // send null to clear override
            // parentIds are always sent for update to handle additions/removals
            parentIds: selectedParentIds,
        };


        try {
            if (elementToEdit?.signatureElementId) {
                 // Check if there are any actual changes to update (excluding parentIds which are always sent)
                 const hasCoreChanges = Object.keys(updatePayload).some(key => key !== 'parentIds');
                 // Fetch original parent IDs to compare accurately - ensure this await is inside the try block
                 let originalParentIds: number[] = [];
                 if (token) { // Check token before API call
                    originalParentIds = elementToEdit.parentElements?.map(p => p.signatureElementId!) ??
                                            (await api.getSignatureElementById(elementToEdit.signatureElementId, ['parents'], token))
                                             .parentElements?.map(p => p.signatureElementId!) ?? [];
                 }


                 if (hasCoreChanges || JSON.stringify(selectedParentIds.sort()) !== JSON.stringify(originalParentIds.sort())) {
                     savedElementResult = await api.updateSignatureElement(elementToEdit.signatureElementId, updatePayload, token);
                 } else {
                     console.log("No changes detected for element update.");
                     toast.info("No changes detected."); // Inform user
                     // Pass back the original element if no changes were made but save was clicked
                     savedElementResult = elementToEdit;
                 }
            } else {
                 savedElementResult = await api.createSignatureElement(createPayload, token);
            }
            onSave(savedElementResult); // Trigger success callback with the result
        } catch (err: any) {
            const msg = err.message || 'Failed to save element';
            setError(msg); toast.error(`Error: ${msg}`); console.error("Save Element Error:", err);
            onSave(null); // Indicate save failed / pass null
        } finally {
            setIsLoading(false);
        }
    };

    if (isFetchingDetails) {
        return <div className='flex justify-center items-center p-10'><LoadingSpinner /></div>;
    }

    return (
        // Use handleSubmit here for validation, but not directly on the form tag
        <div className="grid gap-4 py-4 max-h-[70vh] overflow-y-auto pr-2 relative">
            {error && <ErrorDisplay message={error} className="mb-4"/>}
            {isLoading && <div className='absolute inset-0 bg-background/50 flex items-center justify-center z-10 rounded-md'><LoadingSpinner/></div>}

            {/* Display Current Component Info */}
            <div className='text-sm p-2 bg-muted rounded border'> Component: <Badge variant="secondary">{currentComponent.name}</Badge> ({currentComponent.index_type}) </div>

            {/* Form Fields */}
            <div className="grid gap-1.5">
                <Label htmlFor="elem-name">Element Name *</Label>
                <Input id="elem-name" {...register('name')} aria-invalid={!!errors.name} className={cn(errors.name && "border-destructive")} />
                {errors.name && <p className="text-xs text-destructive">{errors.name.message}</p>}
            </div>
            <div className="grid gap-1.5">
                <Label htmlFor="elem-description">Description (Optional)</Label>
                <Textarea id="elem-description" {...register('description')} rows={3} aria-invalid={!!errors.description} className={cn(errors.description && "border-destructive")} />
                {errors.description && <p className="text-xs text-destructive">{errors.description.message}</p>}
            </div>
            <div className="grid gap-1.5">
                <Label htmlFor="elem-index">Index (Optional - Override Auto-Index)</Label>
                <Input id="elem-index" {...register('index')} placeholder={`Auto (${currentComponent.index_type})`} aria-invalid={!!errors.index} className={cn(errors.index && "border-destructive")} />
                <p className='text-xs text-muted-foreground'>Leave empty for automatic index based on component type.</p>
                {errors.index && <p className="text-xs text-destructive">{errors.index.message}</p>}
            </div>
            <div className="grid gap-1.5">
                 {/* Pass currentElementId to prevent self-selection */}
                <ElementSelector
                    selectedElementIds={selectedParentIds}
                    onChange={setSelectedParentIds}
                    currentElementId={elementToEdit?.signatureElementId}
                    currentComponentId={currentComponent?.signatureComponentId}
                    label="Parent Elements (Optional)"
                />
                <input type="hidden" {...register('parentIds')} />
                {errors.parentIds && <p className="text-xs text-destructive">{typeof errors.parentIds.message === 'string' ? errors.parentIds.message : 'Invalid parent selection'}</p>}
            </div>
            {/*
              Changed Button type to "button" and added onClick handler.
              We manually trigger react-hook-form's handleSubmit which runs validation
              and then calls our handleFormSubmit function if valid.
              This prevents the default form submission behavior.
            */}
            <Button
                type="button"
                onClick={handleSubmit(handleFormSubmit)}
                disabled={isLoading || isFetchingDetails}
                className="mt-2 justify-self-start"
            >
                {isLoading ? <LoadingSpinner size="sm" className='mr-2' /> : (elementToEdit ? 'Update Element' : 'Create Element')}
            </Button>
        </div>
    );
};

export default ElementForm;

// frontend-solid/src/components/signatures/ElementForm.tsx
import { Component, createSignal, createEffect, Show, JSX } from 'solid-js';
// Removed @modular-forms/solid imports
import { z, ZodIssue } from 'zod';
import { elementFormSchema, ElementFormData } from '@/lib/zodSchemas';
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';
import type { SignatureElement, CreateSignatureElementInput, UpdateSignatureElementInput } from '../../../../backend/src/functionalities/signature/element/models';
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';

import { Button } from '@/components/ui/Button';
import { Input, type InputProps } from '@/components/ui/Input';
import { FormLabel } from '@/components/ui/FormLabel';
import { Textarea, type TextareaProps } from '@/components/ui/Textarea';
import { Badge } from '@/components/ui/Badge';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import styles from './ElementForm.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils';
import SignatureSelector from '@/components/shared/SignatureSelector';

interface ElementFormProps {
    elementToEdit: SignatureElement | null;
    currentComponent: SignatureComponent;
    onSave: (savedElement: SignatureElement | null) => void;
}

const ElementForm: Component<ElementFormProps> = (props) => {
    const [authState] = useAuth();
    const [apiError, setApiError] = createSignal<string | null>(null);
    const [isSubmitting, setIsSubmitting] = createSignal(false);
    const [isLoadingDetails, setIsLoadingDetails] = createSignal(false);

    // Form state signals
    const [name, setName] = createSignal('');
    const [description, setDescription] = createSignal<string | null>(null);
    const [index, setIndex] = createSignal<string | null>(null); // Store as string or null
    const [selectedParentPaths, setSelectedParentPaths] = createSignal<number[][]>([]); // For SignatureSelector
    const [formErrors, setFormErrors] = createSignal<Partial<Record<keyof ElementFormData, string>>>({});

    // REMOVED hasErrors check

    // Fetch parent paths and populate form/selector when editing
    createEffect(async () => {
        const element = props.elementToEdit;
        const token = authState.token;
        // Reset form state first
        setName(element?.name ?? '');
        setDescription(element?.description ?? null);
        setIndex(element?.index ?? null); // Use null for empty/auto index
        setSelectedParentPaths([]); // Reset parents initially
        setApiError(null);
        setFormErrors({});
        setIsSubmitting(false);

        if (element?.signatureElementId && token) {
            setIsLoadingDetails(true);
            try {
                // Fetch full details including parents
                const fullElement = await api.getSignatureElementById(element.signatureElementId, ['parents'], token);
                // Extract full parent paths (needs backend support or complex client logic)
                // Assuming backend provides `parentPaths` array on the full element for simplicity
                const parentPaths: number[][] = (fullElement as any).parentPaths || []; // Replace with actual fetch/construction logic
                setSelectedParentPaths(parentPaths);
                // Set other fields from fullElement if they differ (though unlikely if elementToEdit is already detailed)
                setName(fullElement.name);
                // --- FIX: Explicitly handle potential undefined by coercing to null ---
                setDescription(fullElement.description ?? null);
                setIndex(fullElement.index ?? null);
            } catch (err: any) {
                const msg = err.message || "Failed to load element details";
                setApiError(msg);
                console.error("Fetch Element Parents Error:", err);
                setSelectedParentPaths([]); // Reset on error
            } finally {
                setIsLoadingDetails(false);
            }
        } else {
            setIsLoadingDetails(false); // Ensure loading is false for create mode
        }
    });

     // Validation function
     const validateForm = (): boolean => {
         setFormErrors({}); // Clear previous errors
         const formData = {
             name: name(),
             description: description(),
             index: index(), // Pass current index state (string or null)
             // Pass parent IDs based on selector state for validation if needed
             parentIds: selectedParentPaths().map(path => path[path.length - 1]).filter(id => id !== undefined),
         };
         const result = elementFormSchema.safeParse(formData);
         if (!result.success) {
             const errors: Partial<Record<keyof ElementFormData, string>> = {};
             result.error.errors.forEach((err: ZodIssue) => {
                 if (err.path.length > 0) {
                    // Ensure path corresponds to ElementFormData keys
                    errors[err.path[0] as keyof ElementFormData] = err.message;
                 }
             });
             setFormErrors(errors);
             return false;
         }
         // No need to setFormErrors({}) here
         return true;
     };


    const handleSubmit = async (event: Event) => {
        event.preventDefault();
        const token = authState.token;
        if (!token || !props.currentComponent?.signatureComponentId || !validateForm()) { // Validate on submit
            setApiError("Component context, authentication missing, or form invalid.");
            return;
        }
        setApiError(null);
        setIsSubmitting(true);
        let savedElement: SignatureElement | null = null;

        const immediateParentIds = selectedParentPaths().map(path => path[path.length - 1]).filter(id => id !== undefined);
        const finalIndex = index()?.trim() || null; // Set to null if empty or only whitespace

        try {
            const basePayload = {
                 name: name(),
                 description: description() || undefined,
                 index: finalIndex ?? undefined, // Send undefined if null
                 parentIds: immediateParentIds,
             };

            if (props.elementToEdit?.signatureElementId) {
                // Update logic
                const updatePayload: UpdateSignatureElementInput = { parentIds: immediateParentIds };
                let hasCoreChanges = false;
                if (name() !== props.elementToEdit.name) { updatePayload.name = name(); hasCoreChanges = true; }
                if ((description() ?? null) !== (props.elementToEdit.description ?? null)) { updatePayload.description = description() || null; hasCoreChanges = true; }
                if ((finalIndex ?? null) !== (props.elementToEdit.index ?? null)) { updatePayload.index = finalIndex ?? null; hasCoreChanges = true; }

                let originalParentIds = props.elementToEdit.parentElements?.map(p => p.signatureElementId!) ?? [];
                let parentsChanged = JSON.stringify(immediateParentIds.sort()) !== JSON.stringify(originalParentIds.sort());

                if (hasCoreChanges || parentsChanged) {
                     console.log("Updating element:", props.elementToEdit.signatureElementId, updatePayload);
                     savedElement = await api.updateSignatureElement(props.elementToEdit.signatureElementId, updatePayload, token);
                 } else {
                     console.log("No changes detected for element update.");
                     savedElement = props.elementToEdit;
                 }
            } else {
                 // Create logic
                 const createPayload: CreateSignatureElementInput = {
                     ...basePayload,
                     signatureComponentId: props.currentComponent.signatureComponentId!,
                 };
                 console.log("Creating element:", createPayload);
                 savedElement = await api.createSignatureElement(createPayload, token);
            }
            props.onSave(savedElement);
        } catch (err: any) {
            const msg = err.message || 'Failed to save element';
            setApiError(msg);
            console.error("Save Element Error:", err);
            props.onSave(null);
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
         <div class={styles.elementFormContainer}>
             <Show when={isLoadingDetails()}>
                 <div class="flex justify-center p-10"><LoadingSpinner /></div>
             </Show>
             <Show when={!isLoadingDetails()}>
                <form onSubmit={handleSubmit} class={styles.elementFormInner}>
                    <Show when={apiError()}><ErrorDisplay message={apiError() ?? 'Unknown API error'} /></Show> {/* Ensure message */}
                    <Show when={isSubmitting()}><div class={styles.loadingOverlay}><LoadingSpinner /></div></Show>

                    <div class={styles.componentInfo}>
                         Component: <Badge variant="secondary">{props.currentComponent.name}</Badge> (Index: {props.currentComponent.index_type})
                    </div>

                    {/* Name Input */}
                    <div class={styles.formGroup}>
                        <FormLabel for="el-name" required invalid={!!formErrors().name}>Element Name</FormLabel>
                        <Input
                            id="el-name"
                            value={name()}
                            // --- FIX: Removed validateForm() call ---
                            onInput={(e) => { setName(e.currentTarget.value); }}
                            required
                            aria-invalid={!!formErrors().name}
                            aria-errormessage="el-name-error"
                        />
                        <Show when={formErrors().name}><p id="el-name-error" class={styles.errorMessage}>{formErrors().name}</p></Show>
                    </div>

                    {/* Description Textarea */}
                    <div class={styles.formGroup}>
                        <FormLabel for="el-desc" invalid={!!formErrors().description}>Description (Optional)</FormLabel>
                        <Textarea
                            id="el-desc"
                            value={description() ?? ''}
                            // --- FIX: Removed validateForm() call ---
                            onInput={(e) => { setDescription(e.currentTarget.value || null); }}
                            aria-invalid={!!formErrors().description}
                            aria-errormessage="el-desc-error"
                            rows={3}
                         />
                        <Show when={formErrors().description}><p id="el-desc-error" class={styles.errorMessage}>{formErrors().description}</p></Show>
                    </div>

                    {/* Index Input */}
                    <div class={styles.formGroup}>
                         <FormLabel for="el-index" invalid={!!formErrors().index}>Index (Optional - Override Auto)</FormLabel>
                         <Input
                            id="el-index"
                            type="text"
                            value={index() ?? ''}
                            // --- FIX: Removed validateForm() call ---
                            onInput={(e) => { setIndex(e.currentTarget.value || null); }}
                            placeholder={`Auto (${props.currentComponent.index_type})`}
                            aria-invalid={!!formErrors().index}
                            aria-errormessage="el-index-error"
                         />
                         <p class='text-xs text-muted-foreground'>Leave empty for automatic index based on parents.</p>
                         <Show when={formErrors().index}><p id="el-index-error" class={styles.errorMessage}>{formErrors().index}</p></Show>
                    </div>

                    {/* Parent Selector */}
                    <div class={styles.formGroup}>
                        <SignatureSelector
                            label="Parent Elements (Optional)"
                            signatures={selectedParentPaths()}
                            onChange={setSelectedParentPaths}
                            disabled={isSubmitting()}
                            // Pass current element ID to prevent self-selection if needed
                            // currentElementId={props.elementToEdit?.signatureElementId}
                        />
                         {/* Show validation error for parentIds if schema includes it */}
                         <Show when={formErrors().parentIds}><p class={styles.errorMessage}>{formErrors().parentIds}</p></Show>
                    </div>

                    <div class={styles.formActions}>
                         {/* --- FIX: Simplified disabled check --- */}
                        <Button type="submit" disabled={isSubmitting() || isLoadingDetails()}>
                             <Show when={isSubmitting()} fallback={props.elementToEdit ? 'Update Element' : 'Create Element'}>
                                <LoadingSpinner size="sm" class={styles.iconMargin}/> Saving...
                            </Show>
                        </Button>
                    </div>
                </form>
            </Show>
         </div>
    );
};

export default ElementForm;
