// frontend-react/src/components/signatures/ElementsPage.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { PlusCircle, ArrowLeft } from 'lucide-react';
import ElementList from './ElementList';
import ElementForm from './ElementForm';
import SearchBar from '@/components/shared/SearchBar';
import { Pagination } from '@/components/shared/Pagination';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';
import type { SignatureElement, SignatureElementSearchResult } from '../../../../backend/src/functionalities/signature/element/models';
import type { SearchRequest, SearchResponse, SearchQueryElement } from '../../../../backend/src/utils/search';
import { toast } from "sonner";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge'; // Import Badge

const ELEMENTS_PAGE_SIZE = 15;

// New component for displaying Elements of a specific Component
const ElementsPage: React.FC = () => {
    const { componentId: componentIdStr } = useParams<{ componentId: string }>();
    const componentId = parseInt(componentIdStr || '', 10);
    const navigate = useNavigate();
    const { token, user } = useAuth();
    const isAdmin = user?.role === 'admin';

    // --- Component State (for the parent component) ---
    const [parentComponent, setParentComponent] = useState<SignatureComponent | null>(null);
    const [isParentLoading, setIsParentLoading] = useState(true);
    const [parentError, setParentError] = useState<string | null>(null);

    // --- Element State ---
    const [elements, setElements] = useState<SignatureElementSearchResult[]>([]);
    const [isElementsLoading, setIsElementsLoading] = useState(false);
    const [elementsError, setElementsError] = useState<string | null>(null);
    const [editingElement, setEditingElement] = useState<SignatureElement | null>(null);
    const [isElementFormOpen, setIsElementFormOpen] = useState(false);
    const [elementSearchQuery, setElementSearchQuery] = useState<SearchRequest['query']>([]);
    const [currentElementPage, setCurrentElementPage] = useState(1);
    const [totalElements, setTotalElements] = useState(0);
    const [totalElementPages, setTotalElementPages] = useState(1);

    // Fetch Parent Component Details
    useEffect(() => {
        const fetchParent = async () => {
            if (!token || isNaN(componentId)) { // Added NaN check
                setIsParentLoading(false);
                setParentError("Invalid component ID.");
                return;
            }
            setIsParentLoading(true);
            setParentError(null);
            try {
                const fetchedComponent = await api.getSignatureComponentById(componentId, token);
                setParentComponent(fetchedComponent);
            } catch (err: any) {
                const msg = err.message || `Failed to fetch component (ID: ${componentId})`;
                setParentError(msg);
                toast.error(msg);
                console.error("Fetch Parent Component Error:", err);
                setParentComponent(null);
            } finally {
                setIsParentLoading(false);
            }
        };
        fetchParent();
    }, [token, componentId]);

    // Fetch Elements Callback
    const fetchElements = useCallback(async (page = 1, query: SearchRequest['query'] = []) => {
        if (!token || isNaN(componentId)) { // Added NaN check
            setIsElementsLoading(false);
            setElementsError("Component ID or authentication token missing or invalid.");
            return;
        }
        setIsElementsLoading(true);
        setElementsError(null);
        try {
            const componentFilter: SearchQueryElement = { field: 'signatureComponentId', condition: 'EQ', value: componentId, not: false };
            const finalQuery = [...query.filter(q => q.field !== 'signatureComponentId'), componentFilter];
            const searchRequest: SearchRequest = { query: finalQuery, page, pageSize: ELEMENTS_PAGE_SIZE };
            const response = await api.searchSignatureElements(searchRequest, token);
            setElements(response.data);
            setTotalElements(response.totalSize);
            setTotalElementPages(response.totalPages);
            setCurrentElementPage(response.page);
        } catch (err: any) {
             const msg = err.message || 'Failed to fetch elements';
             setElementsError(msg); toast.error(msg); console.error("Fetch Elements Error:", err);
             setElements([]); setTotalElements(0); setTotalElementPages(1);
        } finally { setIsElementsLoading(false); }
    }, [token, componentId]); // Depends on token and componentId

    // Fetch Elements Effect
    useEffect(() => {
        // Fetch only if parent component is loaded and valid
        if (parentComponent) {
            fetchElements(currentElementPage, elementSearchQuery);
        } else {
            // Clear elements if no valid parent
            setElements([]); setTotalElements(0); setTotalElementPages(1); setCurrentElementPage(1);
        }
    }, [parentComponent, currentElementPage, elementSearchQuery, fetchElements]);

    // --- Element CRUD & Other Callbacks ---
    const handleEditElement = useCallback((element: SignatureElement) => {
        setEditingElement(element);
        setIsElementFormOpen(true);
    }, []);

    const handleCreateElement = useCallback(() => {
        if (!parentComponent) { toast.warning("Parent component not loaded."); return; }
        setEditingElement(null);
        setIsElementFormOpen(true);
    }, [parentComponent]);

    const handleDeleteElement = useCallback(async (elementId: number) => {
        if (!parentComponent || !token) {
            toast.error("Parent component or authentication token missing."); return;
        }
        if (!window.confirm("Are you sure you want to delete this element? This may break references.")) return;

        setIsElementsLoading(true); setElementsError(null);
        try {
            await api.deleteSignatureElement(elementId, token);
            toast.success("Element deleted successfully.");
            const newTotalElements = totalElements - 1;
            const newTotalPages = Math.max(1, Math.ceil(newTotalElements / ELEMENTS_PAGE_SIZE));
            const newPage = (currentElementPage > newTotalPages) ? newTotalPages : currentElementPage;

            // Update parent component's count (if we have it) - local state update only
            if (parentComponent && parentComponent.index_count !== undefined && parentComponent.index_count !== null) {
                setParentComponent(prev => prev ? {...prev, index_count: prev.index_count! - 1} : null);
            }

            // Refetch elements for the potentially adjusted page
            await fetchElements(newPage, elementSearchQuery);
            if (currentElementPage !== newPage) {
                setCurrentElementPage(newPage);
            }
        } catch(e: any){
            const msg = e.message || "Failed to delete element";
            setElementsError(msg); toast.error(msg);
        } finally {
            setIsElementsLoading(false);
        }
    }, [token, parentComponent, totalElements, currentElementPage, elementSearchQuery, fetchElements]);

    const handleElementSaveSuccess = useCallback(async (savedElement: SignatureElement | null) => { // Added parameter
        setIsElementFormOpen(false);
        setEditingElement(null);
        // Show success only if an element was actually created/updated
        if (savedElement) {
             toast.success("Element saved successfully.");
        }
        const currentParentId = parentComponent?.signatureComponentId; // Store ID before potential async operations

        // Fixed: Ensure currentParentId is a valid number before proceeding
        if (typeof currentParentId === 'number' && !isNaN(currentParentId)) {
            // Refetch elements for the current page first
            await fetchElements(currentElementPage, elementSearchQuery);

            // Then, fetch parent again to update count only if an element was actually created/updated
             if (savedElement) {
                 try {
                     // Use the stored ID for safety
                     const updatedParent = await api.getSignatureComponentById(currentParentId, token);
                     setParentComponent(updatedParent);
                 } catch (err) {
                     console.error("Failed to refresh parent component after element save", err);
                     // Optionally, manually adjust count if fetch fails
                      // setParentComponent(prev => prev ? {...prev, index_count: (prev.index_count ?? 0) + (editingElement ? 0 : 1)} : null);
                 }
            }
        } else {
            console.warn("Cannot refresh elements or parent: Parent component ID is missing or invalid.");
        }
    }, [parentComponent?.signatureComponentId, currentElementPage, elementSearchQuery, fetchElements, token]); // Add token dependency


    // Element Search & Pagination Handlers
    const handleElementSearch = useCallback((newQuery: SearchRequest['query']) => {
        setElementSearchQuery(newQuery);
        setCurrentElementPage(1); // Reset page on new search
    }, []);
    const handleElementPageChange = useCallback((newPage: number) => {
        setCurrentElementPage(newPage);
    }, []);

    // --- Render ---
    if (isParentLoading) {
        return <div className="flex justify-center items-center h-32"><LoadingSpinner /></div>;
    }
    if (parentError) {
        return <ErrorDisplay message={parentError} />;
    }
    // Check for NaN as well, just in case parseInt failed silently earlier
    if (!parentComponent || isNaN(componentId)) {
        return <ErrorDisplay message={`Component with ID ${componentIdStr || 'invalid'} not found or failed to load.`} />;
    }

    return (
        <div className="space-y-6">
            {/* Page Header */}
            <div className="flex items-center gap-4">
                <Button variant="outline" size="icon" onClick={() => navigate('/signatures')} title="Back to Components">
                    <ArrowLeft className="h-4 w-4" />
                </Button>
                <div>
                    <h1 className="text-2xl font-bold">
                         Elements for: <span className='text-primary'>{parentComponent.name}</span>
                    </h1>
                    <p className='text-muted-foreground'>Manage elements within the selected component.</p>
                    <Badge variant="secondary" className='mt-1'>Index Type: {parentComponent.index_type}</Badge>
                    <Badge variant="outline" className='mt-1 ml-2'>Elements: {parentComponent.index_count ?? 'N/A'}</Badge>
                 </div>
            </div>

            {/* Elements Section */}
            <Card>
                 <CardHeader>
                      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                          <div>
                              <CardTitle>Element List</CardTitle>
                              <CardDescription>Elements defined within the "{parentComponent.name}" component.</CardDescription>
                           </div>
                         <Dialog open={isElementFormOpen} onOpenChange={setIsElementFormOpen}>
                            <DialogTrigger asChild>
                                <Button onClick={handleCreateElement} size="sm" className='shrink-0'>
                                    <PlusCircle className="mr-2 h-4 w-4" /> New Element
                                </Button>
                            </DialogTrigger>
                            <DialogContent className="sm:max-w-[600px]">
                                <DialogHeader><DialogTitle>{editingElement ? 'Edit Element' : 'Create New Element'}</DialogTitle></DialogHeader>
                                {/* Ensure element form only renders when dialog is open and parent is loaded */}
                                {isElementFormOpen && parentComponent && (
                                     <ElementForm
                                        elementToEdit={editingElement}
                                        currentComponent={parentComponent}
                                        onSave={handleElementSaveSuccess}
                                      />
                                )}
                            </DialogContent>
                         </Dialog>
                      </div>
                 </CardHeader>
                 <CardContent className='space-y-4'>
                    {elementsError && <ErrorDisplay message={elementsError} />}
                    {/* Search Bar for Elements */}
                     <SearchBar
                        fields={[
                            { value: 'name', label: 'Name', type: 'text' as const },
                            { value: 'description', label: 'Description', type: 'text' as const},
                            { value: 'index', label: 'Index', type: 'text' as const},
                            { value: 'hasParents', label: 'Has Parents', type: 'boolean' as const },
                         ]}
                        onSearch={handleElementSearch}
                        isLoading={isElementsLoading}
                     />
                    {/* Element List */}
                    {isElementsLoading && <div className='flex justify-center py-10'><LoadingSpinner /></div>}
                    {!isElementsLoading && !elementsError && (
                        <>
                            <ElementList
                                elements={elements}
                                onEdit={handleEditElement}
                                onDelete={handleDeleteElement}
                             />
                            {totalElementPages > 1 && (
                                <div className="mt-4 flex justify-center">
                                    <Pagination
                                        currentPage={currentElementPage}
                                        totalPages={totalElementPages}
                                        onPageChange={handleElementPageChange}
                                     />
                                </div>
                             )}
                            {elements.length === 0 && elementSearchQuery.length === 0 && ( <p className="text-center text-muted-foreground py-6">No elements found for this component. Click "New Element".</p> )}
                            {elements.length === 0 && elementSearchQuery.length > 0 && ( <p className="text-center text-muted-foreground py-6">No elements found matching search criteria.</p> )}
                        </>
                    )}
                 </CardContent>
            </Card>
        </div>
    );
};

export default ElementsPage;

// frontend-solid/src/components/signatures/ElementsPage.tsx
import { Component, createSignal, createResource, Show, createMemo, Suspense, Accessor } from 'solid-js'; // Added Accessor
import { useParams, useNavigate } from '@solidjs/router';
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';
import type { SignatureElement, SignatureElementSearchResult } from '../../../../backend/src/functionalities/signature/element/models';
import type { SearchRequest, SearchQueryElement } from '../../../../backend/src/utils/search';

import { Button } from '@/components/ui/Button';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogBody } from '@/components/ui/Dialog'; // Added DialogBody
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import ElementList from './ElementList';
import ElementForm from './ElementForm';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import SearchBar, { type SearchFieldOption } from '@/components/shared/SearchBar'; // Import SearchBar
import { Pagination } from '@/components/shared/Pagination'; // Import Pagination
import { Icon } from '@/components/shared/Icon';
import styles from './ElementsPage.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils'; // Import cn

const ELEMENTS_PAGE_SIZE = 15;

const ElementsPage: Component = () => {
    const params = useParams<{ componentId: string }>();
    const componentId = () => parseInt(params.componentId || '', 10); // Make componentId reactive
    const navigate = useNavigate();
    const [authState] = useAuth();
    const isAdmin = () => authState.user?.role === 'admin'; // Only admin can edit/delete elements? Assume yes for now.

    // State for forms and dialogs
    const [editingElement, setEditingElement] = createSignal<SignatureElement | null>(null);
    const [isFormOpen, setIsFormOpen] = createSignal(false);

    // State for search/pagination
    const [searchQuery, setSearchQuery] = createSignal<SearchRequest['query']>([]);
    const [currentPage, setCurrentPage] = createSignal(1);

    // --- Resource for Parent Component ---
    const [parentComponentResource, { refetch: refetchParent }] = createResource( // Added refetch
        // Depends on token and componentId() signal
        () => ({ token: authState.token, id: componentId() }),
        async ({ token, id }) => {
            if (!token || isNaN(id)) {
                throw new Error("Invalid component ID or not authenticated.");
            }
            console.log(`Fetching parent component: ${id}`);
            try {
                return await api.getSignatureComponentById(id, token);
            } catch (error) {
                 console.error("Fetch Parent Component Error:", error);
                 // TODO: Toast/Notification
                 throw error; // Let resource handle error state
            }
        }
    );

     // --- Resource for Elements ---
     const [elementsData, { refetch: refetchElements }] = createResource(
         // Depends on token, componentId(), current page, and search query
         () => ({
             token: authState.token,
             id: componentId(),
             page: currentPage(),
             query: searchQuery(),
             // Ensure parent resource has successfully loaded *and* contains data
             parentIsReady: !parentComponentResource.loading && !parentComponentResource.error && !!parentComponentResource()
         }),
         async ({ token, id, page, query, parentIsReady }) => {
             // Guard: Only fetch if dependencies are valid and parent is ready
             if (!token || isNaN(id) || !parentIsReady) {
                 return { data: [], totalSize: 0, totalPages: 1, page: 1 };
             }
             console.log(`Fetching elements for component ${id} - Page: ${page}, Query:`, query);
             const componentFilter: SearchQueryElement = { field: 'signatureComponentId', condition: 'EQ', value: id, not: false };
             const finalQuery = [...query.filter(q => q.field !== 'signatureComponentId'), componentFilter];
             const searchRequest: SearchRequest = { query: finalQuery, page, pageSize: ELEMENTS_PAGE_SIZE };
             try {
                 return await api.searchSignatureElements(searchRequest, token);
             } catch (error) {
                 console.error("Fetch Elements Error:", error);
                 // TODO: Toast/Notification
                 throw error;
             }
         },
         { initialValue: { data: [], totalSize: 0, totalPages: 1, page: 1 } }
     );


    // --- CRUD Handlers ---
    const handleEdit = async (element: SignatureElementSearchResult) => { // Receive SearchResult
        if (!isAdmin() || !authState.token) return; // Guard
        try {
             // Fetch full details before opening editor
             setIsFormOpen(true); // Open dialog immediately to show loading state inside
             setEditingElement(null); // Clear previous editing state
             const fullElement = await api.getSignatureElementById(element.signatureElementId!, ['parents'], authState.token);
             setEditingElement(fullElement); // Set full details
        } catch (err) {
            console.error("Error fetching element details for edit:", err);
            setIsFormOpen(false); // Close dialog on error
            // TODO: Toast error
        }
    };

    const handleCreateNew = () => {
        if (!parentComponentResource() || !isAdmin()) return; // Guard
        setEditingElement(null);
        setIsFormOpen(true);
    };

    const handleDelete = async (elementId: number) => {
        const token = authState.token;
        if (!isAdmin() || !token || !elementId || !parentComponentResource()) return; // Guard
        if (!window.confirm("Are you sure you want to delete this element? This might affect existing archive items.")) return;

        try {
            await api.deleteSignatureElement(elementId, token);
             // TODO: Toast success
             // Refresh list, adjusting page if necessary
             const currentTotal = elementsData()?.totalSize ?? 0;
             const newTotal = currentTotal - 1;
             const newTotalPages = Math.max(1, Math.ceil(newTotal / ELEMENTS_PAGE_SIZE));
             if (currentPage() > newTotalPages && newTotalPages > 0) {
                 setCurrentPage(newTotalPages); // Triggers refetch
             } else {
                 refetchElements();
             }
             // Optionally refetch parent component to update count
             refetchParent(); // Use refetch function
        } catch (err: any) {
            console.error("Delete Element Error:", err);
            // TODO: Toast error
        }
    };

    const handleSaveSuccess = (savedElement: SignatureElement | null) => {
        setIsFormOpen(false);
        if (savedElement) { // Only show toast if save actually happened
            // TODO: Toast success
        }
        refetchElements(); // Refresh the list
        // Optionally refetch parent component to update count
        refetchParent(); // Use refetch function
    };

    // --- Dialog Handler ---
     const handleOpenChange = (open: boolean) => {
         setIsFormOpen(open);
         if (!open) { setEditingElement(null); }
     };

     // --- Search & Pagination Handlers ---
     const handleSearch = (newQuery: SearchRequest['query']) => {
         if (JSON.stringify(newQuery) !== JSON.stringify(searchQuery())) {
            setSearchQuery(newQuery);
            setCurrentPage(1);
         }
     };
     const handlePageChange = (newPage: number) => {
          if (newPage !== currentPage()) {
             setCurrentPage(newPage);
          }
     };

    // --- Search Fields ---
    const elementSearchFields = createMemo((): SearchFieldOption[] => [
        { value: 'name', label: 'Name', type: 'text' as const },
        { value: 'description', label: 'Description', type: 'text' as const},
        { value: 'index', label: 'Index', type: 'text' as const},
        { value: 'hasParents', label: 'Has Parents', type: 'boolean' as const },
        { value: 'parentNames', label: 'Parent Name (Any)', type: 'text' as const }, // Assuming backend supports this
    ]);

    // Map index types to readable labels
    const indexTypeLabels: Record<string, string> = {
        dec: 'Decimal (1, 2)',
        roman: 'Roman (I, II)',
        small_char: 'Letters (a, b)',
        capital_char: 'Capitals (A, B)'
    };

    // Memoize parent component data to avoid re-rendering issues
    const parent = createMemo(() => parentComponentResource());

    return (
        <div class={styles.elementsPageContainer}>
            {/* Header Section */}
             <Show when={parent()}
                  fallback={
                      <div class={styles.elementsHeaderContainer}>
                           <Button variant="outline" size="icon" onClick={() => navigate('/signatures')} title="Back to Components">
                               <Icon name="ArrowLeft" size="1rem"/>
                           </Button>
                           <div class={styles.elementsHeaderContent}>
                               <Show when={parentComponentResource.loading} fallback={<Show when={parentComponentResource.error} fallback={<h1 class={styles.pageTitle}>Component Not Found</h1>}><ErrorDisplay message={`Error loading component: ${parentComponentResource.error?.message}`} /></Show>}>
                                   <div class="flex items-center gap-sm"><LoadingSpinner size="sm"/><span class="text-muted-foreground">Loading Component...</span></div>
                               </Show>
                           </div>
                      </div>
                  }
             >
                  {/* Don't need explicit typing here, Show passes the accessor */}
                  {(resolvedParent) => (
                     <div class={styles.elementsHeaderContainer}>
                          <Button variant="outline" size="icon" onClick={() => navigate('/signatures')} title="Back to Components">
                              <Icon name="ArrowLeft" size="1rem"/>
                          </Button>
                          <div class={styles.elementsHeaderContent}>
                              <h1 class={styles.pageTitle}>
                                  Elements: <span class="text-primary">{resolvedParent().name}</span>
                              </h1>
                              <p class={styles.pageDescription}>{resolvedParent().description || 'Manage elements within this component.'}</p>
                              <div class={styles.componentInfoBadges}>
                                 <Badge variant="secondary">Index: {indexTypeLabels[resolvedParent().index_type] || resolvedParent().index_type}</Badge>
                                 <Badge variant="outline">Count: {resolvedParent().index_count ?? 'N/A'}</Badge>
                              </div>
                          </div>
                      </div>
                  )}
             </Show>

            {/* Elements Section - Render only if parent loaded successfully */}
            {/* Use memoized parent. The Show component passes the unwrapped value to its children. */}
             <Show when={parent() && !parentComponentResource.error}>
                 <Card class={styles.elementsListCard}>
                    <CardHeader class={styles.elementsCardHeader}>
                         <div class="flex-grow">
                             <SearchBar fields={elementSearchFields()} onSearch={handleSearch} isLoading={elementsData.loading} />
                         </div>
                         <Dialog open={isFormOpen()} onOpenChange={handleOpenChange}>
                            <DialogTrigger asChild>
                                <Button onClick={handleCreateNew} size="sm" class={styles.createButtonContainer} disabled={!isAdmin()} title={!isAdmin() ? "Admin required" : "Create New Element"}>
                                    <Icon name="PlusCircle" class={styles.iconMargin}/> New Element
                                </Button>
                            </DialogTrigger>
                            <DialogContent size="md">
                                <DialogHeader><DialogTitle>{editingElement() ? 'Edit Element' : 'Create New Element'}</DialogTitle></DialogHeader>
                                 <DialogBody>
                                     {/* Pass the unwrapped component object from parent() */}
                                    <ElementForm
                                        elementToEdit={editingElement()}
                                        currentComponent={parent()!} // Use non-null assertion as it's guaranteed by Show
                                        onSave={handleSaveSuccess}
                                     />
                                 </DialogBody>
                            </DialogContent>
                        </Dialog>
                    </CardHeader>
                    <CardContent>
                         <Show when={elementsData.error}>
                             <ErrorDisplay message={`Failed to load elements: ${elementsData.error?.message}`} />
                         </Show>
                         <Show when={elementsData.loading && !elementsData()?.data?.length}>
                             <div class={styles.loadingContainer}>
                                 <LoadingSpinner />
                             </div>
                         </Show>
                         <Show when={!elementsData.loading && !elementsData.error && elementsData()}>
                             {(data) => (
                                <Show when={data().data.length > 0}
                                    fallback={<p class={styles.emptyStateText}>{searchQuery().length > 0 ? 'No elements match search.' : 'No elements yet. Create one!'}</p>}
                                >
                                    <ElementList
                                        elements={data().data}
                                        onEdit={handleEdit}
                                        onDelete={handleDelete}
                                    />
                                </Show>
                             )}
                         </Show>
                         <Show when={!elementsData.loading && (elementsData()?.totalPages ?? 0) > 1}>
                             <div class={styles.paginationContainer}>
                                 <Pagination
                                     currentPage={currentPage()}
                                     totalPages={elementsData()?.totalPages ?? 1}
                                     onPageChange={handlePageChange}
                                 />
                             </div>
                         </Show>
                    </CardContent>
                </Card>
            </Show>
        </div>
    );
};

export default ElementsPage;
