// frontend-solid/src/components/signatures/ComponentsPage.tsx
import { Component, createSignal, createResource, Show } from 'solid-js';
import { useAuth } from '@/context/AuthContext';
import api from '@/lib/api';
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';

import { Button } from '@/components/ui/Button';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogBody } from '@/components/ui/Dialog'; // Added DialogBody
import ComponentList from './ComponentList';
import ComponentForm from './ComponentForm';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import { Icon } from '@/components/shared/Icon';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card'; // Added Title/Desc back
import styles from './ComponentsPage.module.css'; // Import CSS Module (Typed)
import { cn } from '@/lib/utils'; // Import cn

const ComponentsPage: Component = () => {
    const [authState] = useAuth();
    const [editingComponent, setEditingComponent] = createSignal<SignatureComponent | null>(null);
    const [isFormOpen, setIsFormOpen] = createSignal(false);

    const isAdmin = () => authState.user?.role === 'admin';

    // Resource to fetch components
    const [componentsResource, { refetch: refetchComponents }] = createResource(
        () => authState.token, // Dependency
        async (token) => {
            if (!token) return [];
            console.log("Fetching signature components...");
            try {
                const fetched = await api.getAllSignatureComponents(token);
                return fetched.sort((a, b) => a.name.localeCompare(b.name));
            } catch (error) {
                console.error("Fetch Components Error:", error);
                // TODO: Toast notification
                throw error;
            }
        },
        { initialValue: [] }
    );

    const handleEdit = (component: SignatureComponent) => {
        if (!isAdmin()) { /* TODO: Toast error */ console.error("Admin required"); return; }
        setEditingComponent(component);
        setIsFormOpen(true);
    };

    const handleCreateNew = () => {
        if (!isAdmin()) return; // Prevent opening dialog if not admin
        setEditingComponent(null);
        setIsFormOpen(true);
    };

    const handleDelete = async (componentId: number) => {
        const token = authState.token;
        if (!isAdmin() || !token) { /* TODO: Toast error */ console.error("Admin required/Not authed"); return; }
        if (!window.confirm("WARNING: Deleting a component also deletes ALL its elements and might affect existing archive items. Are you absolutely sure?")) return;

        try {
            await api.deleteSignatureComponent(componentId, token);
            // TODO: Toast success
            refetchComponents();
        } catch (err: any) {
            console.error("Delete Component Error:", err);
            // TODO: Toast error
        }
    };

     const handleReindex = async (componentId: number) => {
        const token = authState.token;
        if (!isAdmin() || !token) { /* TODO: Toast error */ console.error("Admin required/Not authed"); return; }
        if (!window.confirm(`Re-index elements in component ID ${componentId}? This assigns sequential indices based on current sorting.`)) return;

        try {
            await api.reindexComponentElements(componentId, token);
            // TODO: Toast success
            refetchComponents(); // Refetch to update counts/data potentially
        } catch (err: any) {
            console.error("Reindex Component Error:", err);
            // TODO: Toast error
        }
     };

    const handleSaveSuccess = () => {
        setIsFormOpen(false); // Close dialog
        refetchComponents(); // Refresh list
        // TODO: Toast success
    };

     // Dialog open change handler
     const handleOpenChange = (open: boolean) => {
         setIsFormOpen(open);
         if (!open) { setEditingComponent(null); }
     };

    return (
        <div class={styles.componentsPageContainer}>
            <div class={styles.headerContainer}>
                <div class={styles.headerTextContent}>
                    <h1 class={styles.pageTitle}>Signature Components</h1>
                    <p class={styles.pageDescription}>Define hierarchical components (like folders) for signatures.</p>
                </div>
                 <Dialog open={isFormOpen()} onOpenChange={handleOpenChange}>
                    <DialogTrigger asChild>
                        <Button onClick={handleCreateNew} disabled={!isAdmin()} class={styles.createButtonContainer} title={!isAdmin() ? "Admin required" : "Create New Component"}>
                            <Icon name="PlusCircle" class={styles.iconMargin}/> New Component
                        </Button>
                    </DialogTrigger>
                    <DialogContent size="sm">
                        <DialogHeader>
                            <DialogTitle>{editingComponent() ? 'Edit Component' : 'Create New Component'}</DialogTitle>
                        </DialogHeader>
                         {/* Wrap form in DialogBody for scrolling */}
                         <DialogBody>
                            <ComponentForm componentToEdit={editingComponent()} onSave={handleSaveSuccess} />
                         </DialogBody>
                    </DialogContent>
                </Dialog>
            </div>

            <Card class={styles.componentsListCard}>
                {/* Can add CardHeader for title if desired */}
                {/* <CardHeader><CardTitle>Component List</CardTitle></CardHeader> */}
                <CardContent>
                    <Show when={componentsResource.error}>
                        <ErrorDisplay message={`Failed to load components: ${componentsResource.error?.message}`} />
                    </Show>
                    <Show when={componentsResource.loading}>
                         <div class={styles.loadingContainer}>
                             <LoadingSpinner size="lg" />
                         </div>
                    </Show>
                     <Show when={!componentsResource.loading && !componentsResource.error && componentsResource()}>
                         {(components) => ( // components() is the accessor
                            <Show when={components().length > 0}
                                fallback={<p class={styles.emptyStateText}>No components created yet. {isAdmin() ? 'Click "New Component".' : ''}</p>}
                            >
                                <ComponentList
                                    components={components()}
                                    onEdit={handleEdit}
                                    onDelete={handleDelete}
                                    onReindex={handleReindex}
                                />
                            </Show>
                         )}
                     </Show>
                 </CardContent>
            </Card>
        </div>
    );
};

export default ComponentsPage;

// frontend/src/components/signatures/ComponentsPage.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom'; // Import useNavigate
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { PlusCircle } from 'lucide-react';
import ComponentList from './ComponentList';
import ComponentForm from './ComponentForm';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import ErrorDisplay from '@/components/shared/ErrorDisplay';
import { useAuth } from '@/hooks/useAuth';
import api from '@/lib/api';
import type { SignatureComponent } from '../../../../backend/src/functionalities/signature/component/models';
import { toast } from "sonner";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';
import { t } from '@/translations/utils'; // Import translation utility

// Renamed from SignaturesPage to ComponentsPage
const ComponentsPage: React.FC = () => {
    const { token, user, preferredLanguage } = useAuth(); // Get preferredLanguage
    const navigate = useNavigate(); // Hook for navigation
    const isAdmin = user?.role === 'admin';

    // --- Component State ---
    const [components, setComponents] = useState<SignatureComponent[]>([]);
    const [isComponentsLoading, setIsComponentsLoading] = useState(true);
    const [componentsError, setComponentsError] = useState<string | null>(null);
    const [editingComponent, setEditingComponent] = useState<SignatureComponent | null>(null);
    const [isComponentFormOpen, setIsComponentFormOpen] = useState(false);

    // --- Component Logic ---

    // Fetch components (stable callback)
    const fetchComponents = useCallback(async () => {
        if (!token) {
            setIsComponentsLoading(false);
            setComponents([]);
            return;
        }
        setIsComponentsLoading(true);
        setComponentsError(null);
        try {
            const fetchedComponents = (await api.getAllSignatureComponents(token))
                                        .sort((a, b) => a.name.localeCompare(b.name));
            setComponents(fetchedComponents);
        } catch (err: any) {
            const msg = err.message || t('componentLoadFailedError', preferredLanguage); // Use translated error
            setComponentsError(msg);
            toast.error(t('errorMessageTemplate', preferredLanguage, { message: msg }));
            console.error("Fetch Components Error:", err);
            setComponents([]);
        } finally {
            setIsComponentsLoading(false);
        }
    }, [token, preferredLanguage]); // Add preferredLanguage

    // Effect: Fetch components when token changes
    useEffect(() => {
        fetchComponents();
    }, [fetchComponents]);

    // Component Callbacks
    const handleEditComponent = useCallback((component: SignatureComponent) => {
        if (!isAdmin) { toast.error(t('componentAdminRequiredError', preferredLanguage)); return; }
        setEditingComponent(component);
        setIsComponentFormOpen(true);
    }, [isAdmin, preferredLanguage]); // Add preferredLanguage

    const handleCreateComponent = useCallback(() => {
        setEditingComponent(null);
        setIsComponentFormOpen(true);
    }, []);

    const handleDeleteComponent = useCallback(async (componentId: number) => {
        if (!isAdmin) { toast.error(t('componentAdminRequiredError', preferredLanguage)); return; }
        if (!token) { toast.error(t('componentAuthTokenMissingError', preferredLanguage)); return; }
        if (!window.confirm(t('confirmDeleteComponentMessage', preferredLanguage))) return;

        setIsComponentsLoading(true); setComponentsError(null);
        try {
            await api.deleteSignatureComponent(componentId, token);
            toast.success(t('componentDeletedSuccess', preferredLanguage));
            // Refetch after successful delete
            await fetchComponents();
        } catch(e: any) {
            const msg = e.message || "Failed";
            setComponentsError(t('componentDeleteFailedError', preferredLanguage));
            toast.error(t('errorMessageTemplate', preferredLanguage, { message: t('componentDeleteFailedError', preferredLanguage) + `: ${msg}` }));
            setIsComponentsLoading(false); // Stop loading on error
        }
        // Loading state will be reset by fetchComponents on success
    }, [isAdmin, token, fetchComponents, preferredLanguage]); // Add preferredLanguage

    const handleReindexComponent = useCallback(async (componentId: number) => {
        if (!isAdmin) { toast.error(t('componentAdminRequiredError', preferredLanguage)); return; }
        if (!token) { toast.error(t('componentAuthTokenMissingError', preferredLanguage)); return; }
        if (!window.confirm(t('confirmReindexComponentMessage', preferredLanguage, { componentId }))) return;

        setIsComponentsLoading(true); setComponentsError(null);
        try {
            await api.reindexComponentElements(componentId, token);
            toast.success(t('componentReindexedSuccess', preferredLanguage));
            // Refetch to update counts etc.
            await fetchComponents();
        } catch(e: any) {
            const msg = e.message || "Failed";
            setComponentsError(t('componentReindexFailedError', preferredLanguage));
            toast.error(t('errorMessageTemplate', preferredLanguage, { message: t('componentReindexFailedError', preferredLanguage) + `: ${msg}` }));
            setIsComponentsLoading(false); // Stop loading on error
        }
        // Loading state will be reset by fetchComponents on success
    }, [isAdmin, token, fetchComponents, preferredLanguage]); // Add preferredLanguage

    const handleComponentSaveSuccess = useCallback(() => {
        setIsComponentFormOpen(false);
        setEditingComponent(null);
        toast.success(editingComponent ? t('componentUpdatedSuccess', preferredLanguage) : t('componentCreatedSuccess', preferredLanguage));
        fetchComponents(); // Refetch list after saving
    }, [fetchComponents, editingComponent, preferredLanguage]); // Add preferredLanguage

    // Navigate to Elements Page when a component is clicked
    const handleOpenComponent = useCallback((component: SignatureComponent) => {
        navigate(`/signatures/${component.signatureComponentId}/elements`);
    }, [navigate]);


    // --- Render ---
    return (
        <div className="space-y-6">
            {/* Page Header */}
            <div>
                 {/* Use translated title and description */}
                <h1 className="text-2xl font-bold">{t('signaturesTitle', preferredLanguage)}</h1>
                <p className='text-muted-foreground'>{t('signaturesDescription', preferredLanguage)}</p>
            </div>

            {/* Components Section */}
            <Card>
                <CardHeader>
                     <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                         <div>
                              {/* Use translated title and description */}
                             <CardTitle>{t('componentsTitle', preferredLanguage)}</CardTitle>
                             <CardDescription>{t('clickComponentToViewElements', preferredLanguage)}</CardDescription>
                         </div>
                         {isAdmin ? (
                             <Dialog open={isComponentFormOpen} onOpenChange={setIsComponentFormOpen}>
                                 <DialogTrigger asChild>
                                     {/* Use translated button text */}
                                     <Button onClick={handleCreateComponent} size="sm" className='shrink-0'>
                                         <PlusCircle className="mr-2 h-4 w-4" /> {t('newComponentButton', preferredLanguage)}
                                     </Button>
                                 </DialogTrigger>
                                 <DialogContent className="sm:max-w-[500px]">
                                      {/* Use translated dialog title */}
                                     <DialogHeader><DialogTitle>{editingComponent ? t('editComponentDialogTitle', preferredLanguage) : t('createComponentDialogTitle', preferredLanguage)}</DialogTitle></DialogHeader>
                                     <ComponentForm componentToEdit={editingComponent} onSave={handleComponentSaveSuccess} />
                                 </DialogContent>
                             </Dialog>
                         ) : (
                             <Button size="sm" className='shrink-0' disabled title={t('componentAdminRequiredError', preferredLanguage)}>
                                <PlusCircle className="mr-2 h-4 w-4" /> {t('newComponentButton', preferredLanguage)}
                             </Button>
                         )}
                     </div>
                </CardHeader>
                <CardContent>
                    {componentsError && <ErrorDisplay message={componentsError} />}
                    {isComponentsLoading && <div className='flex justify-center py-6'><LoadingSpinner /></div>}
                    {!isComponentsLoading && !componentsError && (
                        // Pass handleOpenComponent instead of onSelect
                        <ComponentList
                            components={components}
                            onEdit={handleEditComponent}
                            onDelete={handleDeleteComponent}
                            onOpen={handleOpenComponent} // Changed prop name
                            onReindex={handleReindexComponent}
                         />
                    )}
                     {/* Use translated empty state */}
                    {!isComponentsLoading && !componentsError && components.length === 0 && (
                        <p className="text-center text-muted-foreground py-4">{t('noComponentsFound', preferredLanguage)} {isAdmin ? t('clickToCreate', preferredLanguage, { item: t('newComponentButton', preferredLanguage) }) : ''}</p> // TODO: Add clickToCreate key
                    )}
                </CardContent>
            </Card>

            {/* Element section is removed from this page */}

        </div>
    );
};

export default ComponentsPage; // Renamed export
