// frontend-solid/src/context/AuthContext.tsx
import { createContext, useContext, createSignal, createEffect, Accessor, Setter, Component, JSX } from 'solid-js';
import { createStore, SetStoreFunction, Store } from 'solid-js/store';
import api from '@/lib/api';
import type { UserCredentials, UserRole } from '../../../backend/src/functionalities/user/models';
// Notifications handled via NotificationContext

interface AuthState {
    token: string | null;
    user: { userId?: number; login: string; role: UserRole | null } | null;
    isAuthenticated: boolean;
    isLoading: boolean;
    error: string | null;
}

interface AuthActions {
    login: (credentials: UserCredentials) => Promise<boolean>;
    logout: () => Promise<void>;
    register: (credentials: UserCredentials) => Promise<boolean>;
    clearError: () => void;
    _initStateFromStorage: () => void; // Internal action
}

// Combine state and actions for the context value
type AuthContextType = [Store<AuthState>, AuthActions];

const AuthContext = createContext<AuthContextType | undefined>(undefined);

const initialState: AuthState = {
    token: null,
    user: null,
    isAuthenticated: false,
    isLoading: true, // Start true until checked
    error: null,
};

export const AuthProvider: Component<{ children: JSX.Element }> = (props) => {
    const [state, setState] = createStore<AuthState>(initialState);

    const _initStateFromStorage = () => {
        console.log("AuthContext: Checking local storage...");
        try {
            const storedToken = localStorage.getItem('authToken');
            const storedUserLogin = localStorage.getItem('authUserLogin');
            const storedUserRole = localStorage.getItem('authUserRole') as UserRole | null;
            const storedUserIdStr = localStorage.getItem('authUserId');

            if (storedToken && storedUserLogin) {
                const parsedUserId = storedUserIdStr ? parseInt(storedUserIdStr, 10) : undefined;
                // Role validation
                const isValidRole = storedUserRole === 'admin' || storedUserRole === 'regular_user' || storedUserRole === null; // Allow null role
                // User ID validation (must be number or undefined, not NaN)
                const isValidUserId = parsedUserId === undefined || !isNaN(parsedUserId);

                if (isValidRole && isValidUserId) {
                    console.log("AuthContext: Restoring state from storage:", { token: !!storedToken, login: storedUserLogin, role: storedUserRole, userId: parsedUserId });
                    setState({
                        token: storedToken,
                        user: {
                            login: storedUserLogin,
                            role: storedUserRole,
                            userId: parsedUserId,
                        },
                        isAuthenticated: true,
                        isLoading: false,
                        error: null,
                    });
                } else {
                     console.warn("AuthContext: Invalid data found in storage. Clearing.", { role: storedUserRole, userIdStr: storedUserIdStr });
                     localStorage.removeItem('authToken');
                     localStorage.removeItem('authUserLogin');
                     localStorage.removeItem('authUserRole');
                     localStorage.removeItem('authUserId');
                     setState({ ...initialState, isLoading: false }); // Reset state but keep loading false
                }
            } else {
                 console.log("AuthContext: No valid auth data in storage.");
                 setState({ ...initialState, isLoading: false }); // Reset state but keep loading false
            }
        } catch (error) {
             console.error("AuthContext: Error reading from localStorage:", error);
             // Clear potentially corrupted storage
             localStorage.removeItem('authToken');
             localStorage.removeItem('authUserLogin');
             localStorage.removeItem('authUserRole');
             localStorage.removeItem('authUserId');
             setState({ ...initialState, isLoading: false, error: "Failed to initialize authentication state." }); // Reset state
        }
    };

    // Run initialization once on component mount
    _initStateFromStorage(); // Direct call instead of useEffect

    const login = async (credentials: UserCredentials): Promise<boolean> => {
        setState({ isLoading: true, error: null });
        try {
            // The API call now correctly expects the object structure defined in the type argument.
            // fetchApi already handles JSON parsing and error checking.
            const response = await api.login(credentials);

            // Log the response received from fetchApi (should be parsed object now)
            console.log("AuthContext: Parsed Login Response from api.login:", response);

            // Destructure AFTER validation, assuming fetchApi throws on invalid response
            const { token, role, login, userId } = response;

            // Additional paranoia checks (though fetchApi should catch most issues)
            if (!token || !login) {
                 console.error("AuthContext: Missing 'token' or 'login' after api.login:", response);
                 throw new Error("Login response missing token or login.");
            }
             if (userId !== undefined && (typeof userId !== 'number' || isNaN(userId))) {
                 console.error("AuthContext: Invalid 'userId' after api.login:", response);
                 throw new Error("Invalid userId received.");
             }
             if (role && !(role === 'admin' || role === 'regular_user')) {
                 console.warn("AuthContext: Invalid role received after api.login:", role);
                 // Optionally treat as null or regular_user instead of throwing
             }

            localStorage.setItem('authToken', token);
            localStorage.setItem('authUserLogin', login);
            if (role) localStorage.setItem('authUserRole', role); else localStorage.removeItem('authUserRole');
            if (userId !== undefined) localStorage.setItem('authUserId', String(userId)); else localStorage.removeItem('authUserId');

            setState({
                token,
                user: { login, role: role || null, userId }, // Use role or default to null
                isAuthenticated: true,
                isLoading: false,
                error: null,
            });
            console.log(`Login successful: ${login}`);
            return true;
        } catch (err: any) {
            // Use the error message from ApiError if available
            const errorMessage = err instanceof Error ? err.message : 'Login failed';
            console.error("AuthContext: Login failed -", errorMessage, err);
            setState({ token: null, user: null, isAuthenticated: false, isLoading: false, error: errorMessage });
            console.error(`Login error: ${errorMessage}`);
            return false;
        }
    };

    const logout = async (): Promise<void> => {
        const currentToken = state.token;
        console.log("AuthContext: logout called.");
        localStorage.removeItem('authToken');
        localStorage.removeItem('authUserLogin');
        localStorage.removeItem('authUserRole');
        localStorage.removeItem('authUserId');
        setState({ ...initialState, isLoading: false });
        console.log("Logged out locally.");

        if (currentToken) {
            try {
                 console.log("AuthContext: Calling logout API.");
                 await api.logout(currentToken);
            } catch (err: any) {
                 console.error('AuthContext: Logout API call failed:', err);
                 console.warn("Logged out locally, but failed to notify the server.");
            }
        }
    };

    const register = async (credentials: UserCredentials): Promise<boolean> => {
        setState({ isLoading: true, error: null });
        try {
            await api.register(credentials);
            setState({ isLoading: false, error: null });
            console.log("Registration successful! Please log in.");
            return true;
        } catch (err: any) {
            const errorMessage = err instanceof Error ? err.message : 'Registration failed';
            console.error("AuthContext: Registration failed -", errorMessage);
            setState({ isLoading: false, error: errorMessage });
             console.error(`Registration error: ${errorMessage}`);
            return false;
        }
    };

    const clearError = () => {
        setState({ error: null });
    };

    const actions: AuthActions = {
        login,
        logout,
        register,
        clearError,
        _initStateFromStorage
    };

    const contextValue: AuthContextType = [state, actions];

    return (
        <AuthContext.Provider value={contextValue}>
            {props.children}
        </AuthContext.Provider>
    );
};

// Custom hook to use the Auth context
export function useAuth(): AuthContextType {
    const context = useContext(AuthContext);
    if (!context) {
        throw new Error("useAuth must be used within an AuthProvider");
    }
    return context;
}

// frontend/src/context/AuthContext.tsx
import React, { createContext, useState, useEffect, ReactNode, useCallback } from 'react';
import api from '@/lib/api';
// Correct the import path assuming backend/src is sibling to frontend/src
import type { UserCredentials, UserRole } from '../../../backend/src/functionalities/user/models';
import { toast } from "sonner"; // Import toast

interface AuthState {
  token: string | null;
  user: { userId?: number; login: string; role: UserRole | null } | null; // Added userId potentially
  isAuthenticated: boolean;
  isLoading: boolean;
  error: string | null;
}

interface AuthContextProps extends AuthState {
  login: (credentials: UserCredentials) => Promise<boolean>; // Return boolean for success
  logout: () => Promise<void>;
  register: (credentials: UserCredentials) => Promise<boolean>; // Return boolean for success
  clearError: () => void;
}

const AuthContext = createContext<AuthContextProps | undefined>(undefined);

const initialState: AuthState = {
  token: null,
  user: null,
  isAuthenticated: false,
  isLoading: true, // Start loading to check localStorage
  error: null,
};

export const AuthProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [state, setState] = useState<AuthState>(initialState);

  // Check localStorage on initial load
  useEffect(() => {
    const storedToken = localStorage.getItem('authToken');
    const storedUserLogin = localStorage.getItem('authUserLogin');
    const storedUserRole = localStorage.getItem('authUserRole') as UserRole | null;
    const storedUserIdStr = localStorage.getItem('authUserId'); // Get User ID if stored

    if (storedToken && storedUserLogin) {
        // Basic validation - might want to add a checkToken API call here for robustness
        if (storedUserRole === 'admin' || storedUserRole === 'regular_user') {
             setState({
                token: storedToken,
                user: {
                    login: storedUserLogin,
                    role: storedUserRole,
                    userId: storedUserIdStr ? parseInt(storedUserIdStr, 10) : undefined // Parse stored User ID
                },
                isAuthenticated: true,
                isLoading: false,
                error: null,
             });
        } else {
            // Clear invalid stored data
             localStorage.removeItem('authToken');
             localStorage.removeItem('authUserLogin');
             localStorage.removeItem('authUserRole');
             localStorage.removeItem('authUserId');
             setState(prevState => ({ ...prevState, isLoading: false }));
        }
    } else {
        setState(prevState => ({ ...prevState, isLoading: false }));
    }
  }, []);


  const login = useCallback(async (credentials: UserCredentials): Promise<boolean> => {
    setState(prevState => ({ ...prevState, isLoading: true, error: null }));
    try {
      // Assuming backend login might return userId along with token, role, login
      const { token, role, login, userId } = await api.login(credentials) as any; // Cast to any or update API type if userId returned
      localStorage.setItem('authToken', token);
      localStorage.setItem('authUserLogin', login);
      localStorage.setItem('authUserRole', role || ''); // Store role
      if (userId) localStorage.setItem('authUserId', String(userId)); // Store userId if returned

      setState({
        token,
        user: { login, role, userId }, // Include userId in state
        isAuthenticated: true,
        isLoading: false,
        error: null,
      });
      toast.success(`Welcome back, ${login}!`);
      return true; // Indicate success
    } catch (err: any) {
      const errorMessage = err.message || 'Login failed';
      setState(prevState => ({
        ...prevState,
        token: null, // Ensure token/user are null on failure
        user: null,
        isAuthenticated: false,
        isLoading: false,
        error: errorMessage,
      }));
      toast.error(errorMessage);
      return false; // Indicate failure
    }
  }, []);

  const logout = useCallback(async () => {
    const currentToken = state.token; // Get token before clearing state
    const currentLogin = state.user?.login;

     // Clear local state and storage immediately
     localStorage.removeItem('authToken');
     localStorage.removeItem('authUserLogin');
     localStorage.removeItem('authUserRole');
     localStorage.removeItem('authUserId'); // Clear userId too
     setState({ ...initialState, isLoading: false }); // Reset to initial, set loading false
     if (currentLogin) {
        toast.info(`User ${currentLogin} logged out.`); // Use previous login name for message
     } else {
        toast.info("Logged out.");
     }


    try {
        if (currentToken) {
           await api.logout(currentToken);
           // API call succeeded, state already updated
        }
    } catch (err: any) {
      // Log error but don't block logout on the frontend
      console.error('Logout API call failed:', err);
       // State is already reset
       toast.warning("Logged out locally, but failed to notify the server.");
    } finally {
        // Ensure loading is false even if API fails
        // Already set to false when resetting state above
    }
  }, [state.token, state.user?.login]); // Depend on token and user for message

  const register = useCallback(async (credentials: UserCredentials): Promise<boolean> => {
    setState(prevState => ({ ...prevState, isLoading: true, error: null }));
    try {
      await api.register(credentials);
      setState(prevState => ({ ...prevState, isLoading: false, error: null }));
      toast.success("Registration successful! Please log in.");
      return true; // Indicate success
    } catch (err: any) {
      const errorMessage = err.message || 'Registration failed';
      setState(prevState => ({
        ...prevState,
        isLoading: false,
        error: errorMessage,
      }));
      toast.error(errorMessage);
      return false; // Indicate failure
    }
  }, []);

  const clearError = useCallback(() => {
      setState(prevState => ({ ...prevState, error: null }));
  }, []);


  return (
    <AuthContext.Provider value={{ ...state, login, logout, register, clearError }}>
      {children}
    </AuthContext.Provider>
  );
};

export default AuthContext;

// Export useAuth hook from here for convenience
export { useAuth } from '@/hooks/useAuth';
