// frontend-solid/src/App.tsx
import { Component, JSX, lazy, Show, Suspense } from 'solid-js';
// RouteDefinition is problematic for nested index routes, simplifying
// import { Router, Route, Navigate, useLocation, A, type RouteDefinition } from '@solidjs/router';
import { Router, Route, Navigate, useLocation, A } from '@solidjs/router'; // Removed RouteDefinition import
import { AuthProvider, useAuth } from '@/context/AuthContext';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
import styles from './App.module.css'; // Import CSS Module (Now typed via global.d.ts)

// Layouts
const MainLayout = lazy(() => import('@/components/layout/Layout'));
const AuthLayout = lazy(() => import('@/components/auth/AuthLayout'));

// Pages (Keep lazy loading)
const LoginPage = lazy(() => import('@/components/auth/LoginPage'));
const RegisterPage = lazy(() => import('@/components/auth/RegisterPage'));
const DashboardPage = lazy(() => import('@/components/dashboard/DashboardPage'));
const NotesPage = lazy(() => import('@/components/notes/NotesPage'));
const TagsPage = lazy(() => import('@/components/tags/TagsPage'));
const ComponentsPage = lazy(() => import('@/components/signatures/ComponentsPage'));
const ElementsPage = lazy(() => import('@/components/signatures/ElementsPage'));
const ArchivePage = lazy(() => import('@/components/archive/ArchivePage'));
const AdminPage = lazy(() => import('@/components/admin/AdminPage'));

// Auth Components
import ProtectedRoute from '@/components/auth/ProtectedRoute';

// Loading fallback component
const FullPageLoader: Component = () => (
    <div class={`${styles.appContainer} ${styles.centered}`}>
        <LoadingSpinner size="lg" />
    </div>
);

// --- REMOVED getRedirectPath helper ---

// --- Define routes using JSX structure for clarity and nesting ---
const AppRoutes: Component = () => {
    // Remove useLocation from here
    const [authState] = useAuth();

    // Define component for Login route to use useLocation internally
    const LoginRouteComponent: Component = () => {
        const location = useLocation(); // Call useLocation *inside* the route component
        const state = location.state as { from?: string } | null | undefined;
        const redirectPath = state?.from || "/"; // Calculate redirect path here

        return (
            <Show when={!authState.isAuthenticated} fallback={<Navigate href={redirectPath} />}>
                <Suspense fallback={<FullPageLoader />}>
                    <AuthLayout>
                        <LoginPage />
                    </AuthLayout>
                </Suspense>
            </Show>
        );
    };

    // Define component for Register route
    const RegisterRouteComponent: Component = () => {
         const location = useLocation(); // Call useLocation *inside* the route component
         const state = location.state as { from?: string } | null | undefined;
         const redirectPath = state?.from || "/"; // Calculate redirect path here

        return (
            <Show when={!authState.isAuthenticated} fallback={<Navigate href={redirectPath} />}>
                <Suspense fallback={<FullPageLoader />}>
                    <AuthLayout>
                        <RegisterPage />
                    </AuthLayout>
                </Suspense>
            </Show>
        );
    };


    return (
        <>
            {/* Public Routes */}
            {/* Use the specific route components */}
            <Route path="/login" component={LoginRouteComponent} />
            <Route path="/register" component={RegisterRouteComponent} />

             {/* Protected Routes Container */}
             {/* Apply Protection Layer using component prop of Route */}
             <Route path="/" component={ProtectedRoute}>
                 {/* Apply Main Layout */}
                 <Route path="/" component={MainLayout}>
                      {/* Default Route (Dashboard) */}
                      <Route path="/" component={() => <Suspense fallback={<LoadingSpinner />}><DashboardPage /></Suspense>} />
                      {/* Other Protected Routes */}
                      <Route path="/notes" component={() => <Suspense fallback={<LoadingSpinner />}><NotesPage /></Suspense>} />
                      <Route path="/tags" component={() => <Suspense fallback={<LoadingSpinner />}><TagsPage /></Suspense>} />
                      <Route path="/signatures">
                          {/* Default signature route */}
                          <Route path="/" component={() => <Suspense fallback={<LoadingSpinner />}><ComponentsPage /></Suspense>} />
                          {/* Nested signature route */}
                          <Route path="/:componentId/elements" component={() => <Suspense fallback={<LoadingSpinner />}><ElementsPage /></Suspense>} />
                      </Route>
                      <Route path="/archive" component={() => <Suspense fallback={<LoadingSpinner />}><ArchivePage /></Suspense>} />
                      <Route path="/admin" component={() => (
                         // Specific role protection for Admin page
                         <ProtectedRoute allowedRoles={['admin']}>
                              <Suspense fallback={<LoadingSpinner />}><AdminPage /></Suspense>
                         </ProtectedRoute>
                      )} />
                      {/* Catch-all INSIDE protected layout */}
                      <Route path="*all" component={() => <Navigate href="/" />} />
                 </Route>
             </Route>

             {/* Top-level Catch-all (if no other route matches) */}
             <Route path="*all" component={() => <Navigate href="/login" />} />
        </>
    );
};

// Main App Content manages routing logic based on auth state
const AppContent: Component = () => {
    const [authState] = useAuth(); // Get only the state part

    return (
        <Show
            when={!authState.isLoading}
            fallback={<FullPageLoader />}
        >
             {/* Router now renders the AppRoutes component */}
             <Router>
                 <AppRoutes />
             </Router>
        </Show>
    );
};

// Main App component wrapping everything with providers
const App: Component = () => {
    return (
        // AuthProvider needs to wrap the part of the app that uses useAuth,
        // which includes the Router and its routes.
        <AuthProvider>
            <AppContent />
        </AuthProvider>
    );
};

export default App;

// frontend-react/src/App.tsx
import React from 'react';
import { Routes, Route, Navigate, useLocation, useNavigate } from 'react-router-dom';
import { AuthProvider } from '@/context/AuthContext';
import { useAuth } from '@/hooks/useAuth';
import Layout from '@/components/layout/Layout';
import LoginForm from '@/components/auth/LoginForm';
import RegisterForm from '@/components/auth/RegisterForm';
import AuthLayout from '@/components/auth/AuthLayout'; // Import the new AuthLayout
import NotesPage from '@/components/notes/NotesPage';
import TagsPage from '@/components/tags/TagsPage';
import ComponentsPage from '@/components/signatures/ComponentsPage';
import ElementsPage from '@/components/signatures/ElementsPage';
import ArchivePage from '@/components/archive/ArchivePage';
import AdminPage from '@/components/admin/AdminPage';
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import LoadingSpinner from '@/components/shared/LoadingSpinner';
// UserRole includes 'employee', 'user'
import type { UserRole } from '../../backend/src/functionalities/user/models';

// Simple Dashboard component
const DashboardPage = () => {
    const { user } = useAuth();
    return (
        <div className="p-4 md:p-6 space-y-4">
            <h1 className="text-2xl font-semibold">Welcome, {user?.login}!</h1>
            <p className="text-muted-foreground">
                 {user?.role === 'user'
                    ? "Use the sidebar to search the archive."
                    : "Select a section from the sidebar to get started."}
            </p>
             {/* Optionally add role-specific dashboard info here */}
        </div>
    );
};


// Main App Content manages routing logic
function AppContent() {
    const { isAuthenticated, isLoading } = useAuth();
    const location = useLocation();
    const navigate = useNavigate();

    if (isLoading) {
        return (
            <div className="flex justify-center items-center min-h-screen w-full bg-background">
                <LoadingSpinner />
            </div>
        );
    }

    // AuthLayout is now a separate component

    return (
        <Routes>
            {/* --- Public Routes (Login/Register) --- */}
            <Route path="/login" element={
                !isAuthenticated ? (
                    <AuthLayout> <LoginForm onSwitchToRegister={() => navigate('/register', { replace: true, state: location.state })} /> </AuthLayout>
                ) : ( <Navigate to={location.state?.from?.pathname || "/"} replace /> )
            } />
            <Route path="/register" element={
                 !isAuthenticated ? (
                    <AuthLayout> <RegisterForm onSwitchToLogin={() => navigate('/login', { replace: true, state: location.state })} /> </AuthLayout>
                 ) : ( <Navigate to={location.state?.from?.pathname || "/"} replace /> )
            } />

            {/* --- Protected Routes (Inside Main Layout) --- */}
            <Route element={<ProtectedRoute />}>
                <Route element={<Layout />}> {/* Main App Layout */}
                    <Route index element={<DashboardPage />} />
                    {/* Archive access for all roles (permissions handled inside) */}
                    <Route path="archive" element={<ArchivePage />} />
                    {/* Employee & Admin Routes */}
                    <Route element={<ProtectedRoute allowedRoles={['admin', 'employee']} />}>
                        <Route path="signatures" element={<ComponentsPage />} />
                        <Route path="signatures/:componentId/elements" element={<ElementsPage />} />
                        <Route path="tags" element={<TagsPage />} />
                        <Route path="notes" element={<NotesPage />} />
                    </Route>
                    {/* Admin Only Routes */}
                    <Route element={<ProtectedRoute allowedRoles={['admin']} />}>
                        <Route path="admin" element={<AdminPage />} />
                    </Route>
                    {/* Fallback inside Layout */}
                    <Route path="*" element={<Navigate to="/" replace />} />
                </Route>
            </Route>

             {/* --- Catch-all Fallback (Redirect to Login if not authenticated) --- */}
             <Route path="*" element={<Navigate to="/login" replace />} />

        </Routes>
    );
}

// Main App component wrapping everything with AuthProvider
function App() {
    return (
        <AuthProvider>
            <AppContent />
        </AuthProvider>
    );
}

export default App;
